-- 관리자 대시보드(admin/) 전용 통계. Supabase SQL editor에서 이 파일 내용을 그대로 실행하세요.
-- 여러 번 실행해도 안전합니다(idempotent). schema.sql과는 별개 파일인데, 앱이 돌아가는 데
-- 필요한 것과 관리자가 들여다보는 것을 섞지 않기 위해서다.
--
-- 여기 만드는 것들은 전부 서비스 롤(서버)만 쓸 수 있다. 대시보드는 주소만 알면 누구나
-- 열리는 정적 HTML이라, 브라우저가 직접 데이터베이스를 읽게 하면 통계 전체가 공개되는
-- 셈이다. 그래서 브라우저 → admin-stats Edge Function(로그인 + 관리자 명단 확인)
-- → 이 함수 순서로만 흐른다.

-- ===================== 관리자 명단 =====================

-- 관리자 대시보드에 들어올 수 있는 사람. 앱과 같은 계정으로 로그인하되, 여기 이름이
-- 올라 있는 사람만 통계를 본다.
--
-- 계정에 'is_admin' 같은 칸을 두지 않고 별도 표로 두는 이유: 관리자는 앱의 개념이 아니라
-- 운영의 개념이다. 앱 어디에서도 "내가 관리자인가"를 묻지 않으므로 앱 데이터에 섞을 이유가
-- 없고, 표를 따로 두면 이 파일 하나만 봐도 누가 들어올 수 있는지 한눈에 보인다.
--
-- 빼는 것도 한 줄이면 된다(delete). 예전 방식(공유 비밀 토큰)은 한 사람을 빼려면 토큰을
-- 바꾸고 함수를 다시 배포해야 했는데, 그러면 나머지 관리자도 전부 다시 설정해야 했다.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  -- 화면에 누구인지 보여주고, 나중에 명단을 볼 때 uuid만 늘어놓지 않으려고 함께 적어둔다.
  email text,
  memo text,
  created_at timestamptz not null default now()
);

-- 사용자가 직접 볼 일도 고칠 일도 없다. 정책을 하나도 만들지 않아서
-- (RLS는 켜져 있고 정책이 없으면 아무것도 통과하지 못한다) 서버만 다룬다.
-- 특히 "내가 관리자인지" 조차 앱에서 물어볼 수 없어야 한다. 명단이 읽히면 누구를 노려야
-- 하는지 알려주는 셈이기 때문이다.
alter table public.admin_users enable row level security;

-- ⚠️ 첫 관리자는 여기서 직접 넣어야 한다. 아래 이메일을 본인 것으로 바꿔 한 번 실행하세요.
--    (앱에 한 번이라도 로그인한 계정이어야 auth.users에 있어서 등록됩니다.)
--
--    insert into public.admin_users (user_id, email, memo)
--    select id, email, '최초 관리자' from auth.users where email = '여기에@본인이메일.com'
--    on conflict (user_id) do nothing;
--
-- 나중에 관리자를 빼려면:
--    delete from public.admin_users where email = '뺄사람@이메일.com';
--
-- 지금 명단을 보려면:
--    select email, memo, created_at from public.admin_users order by created_at;

-- ===================== AI 호출 기록 =====================

-- api_usage_total은 "몇 번 불렀나"만 세서 요금을 어림잡을 수밖에 없다. AI 요금은 실제로는
-- 토큰 수로 매겨지므로, 호출마다 모델과 토큰 수를 적어두면 비용을 어림이 아니라 계산으로
-- 알 수 있다. 기록은 Edge Function(analyze-gifticon, search-price)이 응답을 받은 뒤 남긴다.
create table if not exists public.ai_usage_log (
  id bigint generated by default as identity primary key,
  action text not null,              -- analyze | price
  model text not null,               -- claude-haiku-4-5 등
  input_tokens int not null default 0,
  output_tokens int not null default 0,
  -- 가격 검색은 웹 검색 도구를 쓰는데, 검색 1회마다 토큰과 별도의 요금이 붙는다($10/1,000회).
  web_search_requests int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_log_created_at_idx on public.ai_usage_log (created_at);

-- 사용자가 직접 볼 일도 고칠 일도 없다. 정책을 하나도 만들지 않아서
-- (RLS는 켜져 있고 정책이 없으면 아무것도 통과하지 못한다) 서버만 다룬다.
alter table public.ai_usage_log enable row level security;

-- ===================== 통계 함수 =====================

-- 대시보드가 그리는 모든 숫자를 한 번에 돌려준다. 화면에서 쿼리를 여러 번 나눠 부르면
-- 부를 때마다 권한을 따져야 하고, 숫자끼리 시점이 어긋난다(집계 도중 데이터가 바뀌면
-- 카드마다 다른 순간을 보게 된다). 한 함수에서 다 세면 둘 다 해결된다.
--
-- 날짜 묶음 기준: 앱 데이터(가입, 등록, 사용)는 한국 시간(Asia/Seoul) 날짜로 묶는다.
-- 관리자가 한국에서 보는 화면이라 "오늘"이 한국의 오늘이어야 자연스럽다.
-- 단 api_usage_total의 day 컬럼은 bump_api_usage가 UTC 날짜로 적으므로 그대로 둔다
-- (다시 묶을 원본 시각이 없다). 하루 경계가 9시간 어긋날 수 있다는 뜻인데,
-- 호출량 추이를 보는 데는 지장이 없다.
create or replace function public.admin_dashboard_stats()
returns json
language sql
security definer
set search_path = public
stable
as $$
  with kst as (
    select (now() at time zone 'Asia/Seoul')::date as today
  ),

  -- ---------- 사용자 ----------
  users_by_month as (
    select to_char(created_at at time zone 'Asia/Seoul', 'YYYY-MM') as month, count(*) as count
    from auth.users
    group by 1 order by 1
  ),
  users_by_day as (
    select (created_at at time zone 'Asia/Seoul')::date as day, count(*) as count
    from auth.users
    where created_at >= now() - interval '180 days'
    group by 1 order by 1
  ),

  -- ---------- 기프티콘 ----------
  -- hidden_at이 있는 것(가족을 나간 사람 것)은 앱 화면에는 안 보이지만, "지금까지 업로드된
  -- 수"에는 포함해서 센다. 대신 hidden 수를 따로 알려줘서 구분할 수 있게 한다.
  g as (
    select
      count(*) as total,
      count(*) filter (where hidden_at is not null) as hidden,
      count(*) filter (where status = 'used') as used,
      count(*) filter (where status <> 'used' and expires_at is not null
                       and expires_at < (select today from kst)) as expired,
      count(*) filter (where status <> 'used' and (expires_at is null
                       or expires_at >= (select today from kst))) as unused,
      coalesce(sum(amount), 0) as amount_total,
      coalesce(sum(amount) filter (where status = 'used'), 0) as amount_used,
      coalesce(sum(amount) filter (where status <> 'used' and expires_at is not null
                                   and expires_at < (select today from kst)), 0) as amount_expired,
      coalesce(sum(amount) filter (where status <> 'used' and (expires_at is null
                                   or expires_at >= (select today from kst))), 0) as amount_unused,
      count(*) filter (where amount is null) as no_amount
    from public.gifticons
  ),
  g_by_day as (
    select (created_at at time zone 'Asia/Seoul')::date as day,
           count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    where created_at >= now() - interval '180 days'
    group by 1 order by 1
  ),
  g_by_month as (
    select to_char(created_at at time zone 'Asia/Seoul', 'YYYY-MM') as month,
           count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    group by 1 order by 1
  ),
  g_used_by_day as (
    select used_at as day, count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    where status = 'used' and used_at is not null and used_at >= (select today from kst) - 180
    group by 1 order by 1
  ),
  g_used_by_month as (
    select to_char(used_at, 'YYYY-MM') as month, count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    where status = 'used' and used_at is not null
    group by 1 order by 1
  ),
  g_categories as (
    select category, count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    group by 1 order by count(*) desc
  ),
  g_brands as (
    select coalesce(nullif(btrim(brand), ''), '(브랜드 없음)') as brand,
           count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    group by 1 order by count(*) desc
    limit 10
  ),
  -- 등록에서 사용까지 걸린 평균 일수. 관리 지표라기보다 "가족들이 실제로 잘 꺼내 쓰는가"를
  -- 보여주는 숫자다. used_at은 날짜만 있어서 등록 시각도 한국 날짜로 맞춰 뺀다.
  g_avg_use as (
    select round(avg(used_at - (created_at at time zone 'Asia/Seoul')::date), 1) as days
    from public.gifticons
    where status = 'used' and used_at is not null
  ),

  -- ---------- 가족 ----------
  f as (
    select
      (select count(*) from public.families) as families,
      (select count(*) from public.family_members) as members
  ),
  f_sizes as (
    select size, count(*) as families
    from (select count(*) as size from public.family_members group by family_id) t
    group by 1 order by 1
  ),
  f_by_month as (
    select to_char(created_at at time zone 'Asia/Seoul', 'YYYY-MM') as month, count(*) as count
    from public.families
    group by 1 order by 1
  ),

  -- ---------- 활동/기타 ----------
  etc as (
    select
      (select count(*) from public.push_subscriptions) as push_subscriptions,
      (select count(*) from public.family_join_requests where status = 'pending') as pending_join_requests,
      (select count(*) from public.gifticons
        where status <> 'used' and expires_at is not null
          and expires_at >= (select today from kst)
          and expires_at < (select today from kst) + 7) as expiring_7d,
      (select count(*) from public.gifticons
        where status <> 'used' and expires_at is not null
          and expires_at >= (select today from kst)
          and expires_at < (select today from kst) + 30) as expiring_30d
  ),
  -- 그날 돈 나가는 기능을 한 번이라도 쓴 사람 수. 정확한 DAU는 아니지만(그냥 열어보기만 한
  -- 사람은 안 잡힌다) 별도 로그 없이 활동 추이를 볼 수 있는 가장 가까운 숫자다.
  active_by_day as (
    select day, count(distinct user_id) as users
    from public.api_usage
    group by 1 order by 1
  ),

  -- ---------- API / AI 호출 ----------
  api_daily as (
    select action, day, count from public.api_usage_total order by day, action
  ),
  ai_daily as (
    select (created_at at time zone 'Asia/Seoul')::date as day, action, model,
           count(*) as calls,
           sum(input_tokens) as input_tokens,
           sum(output_tokens) as output_tokens,
           sum(web_search_requests) as web_search_requests
    from public.ai_usage_log
    group by 1, 2, 3 order by 1
  )

  select json_build_object(
    'generated_at', now(),
    'users', json_build_object(
      'total', (select count(*) from auth.users),
      'by_day', (select coalesce(json_agg(u), '[]'::json) from users_by_day u),
      'by_month', (select coalesce(json_agg(u), '[]'::json) from users_by_month u)
    ),
    'families', json_build_object(
      'total', (select families from f),
      'members', (select members from f),
      'size_distribution', (select coalesce(json_agg(s), '[]'::json) from f_sizes s),
      'by_month', (select coalesce(json_agg(m), '[]'::json) from f_by_month m)
    ),
    'gifticons', json_build_object(
      'total', (select total from g),
      'unused', (select unused from g),
      'used', (select used from g),
      'expired', (select expired from g),
      'hidden', (select hidden from g),
      'no_amount', (select no_amount from g),
      'amount_total', (select amount_total from g),
      'amount_unused', (select amount_unused from g),
      'amount_used', (select amount_used from g),
      'amount_expired', (select amount_expired from g),
      'avg_days_to_use', (select days from g_avg_use),
      'by_day', (select coalesce(json_agg(d), '[]'::json) from g_by_day d),
      'by_month', (select coalesce(json_agg(m), '[]'::json) from g_by_month m),
      'used_by_day', (select coalesce(json_agg(d), '[]'::json) from g_used_by_day d),
      'used_by_month', (select coalesce(json_agg(m), '[]'::json) from g_used_by_month m),
      'categories', (select coalesce(json_agg(c), '[]'::json) from g_categories c),
      'brands', (select coalesce(json_agg(b), '[]'::json) from g_brands b)
    ),
    'engagement', json_build_object(
      'push_subscriptions', (select push_subscriptions from etc),
      'pending_join_requests', (select pending_join_requests from etc),
      'expiring_7d', (select expiring_7d from etc),
      'expiring_30d', (select expiring_30d from etc),
      'active_by_day', (select coalesce(json_agg(a), '[]'::json) from active_by_day a)
    ),
    'api_usage_daily', (select coalesce(json_agg(a), '[]'::json) from api_daily a),
    'ai_usage_daily', (select coalesce(json_agg(a), '[]'::json) from ai_daily a)
  );
$$;

-- 이 함수는 auth.users까지 읽는다(security definer). 브라우저에서 부를 수 있으면
-- 로그인한 아무나 전체 통계를 보게 되므로, 서버(Edge Function의 서비스 롤)만 부른다.
revoke all on function public.admin_dashboard_stats() from public;
revoke all on function public.admin_dashboard_stats() from anon;
revoke all on function public.admin_dashboard_stats() from authenticated;
grant execute on function public.admin_dashboard_stats() to service_role;

-- ===================== 관리 목록 (회원 / 기프티콘 / 가족) =====================
--
-- 대시보드 왼쪽 탭에서 쓰는 목록들. 통계와 달리 "한 줄 한 줄"을 보는 화면이라 검색과
-- 페이지 나누기가 필요하다. 세 함수 모두 { total, rows } 형태로 돌려준다 —
-- total이 있어야 화면에서 "몇 건 중 몇 번째"를 보여줄 수 있다.
--
-- ⚠️ 바코드 번호(gifticons.code)와 사진 경로는 어느 목록에도 넣지 않는다. 바코드는 그
-- 자체가 돈이라, 운영하려고 만든 화면이 정작 가장 위험한 값을 한 화면에 펼쳐 보이면
-- 안 된다. 관리에 필요한 것은 "무엇이 몇 장 있고 어떤 상태인가"지 번호가 아니다.

-- 회원 목록. auth.users가 원본이고, 앱에서의 활동을 함께 붙여 보여준다.
create or replace function public.admin_list_users(
  q text default null,
  page_size int default 50,
  page_offset int default 0
)
returns json
language sql
security definer
set search_path = public
stable
as $$
  with base as (
    select u.id, u.email, u.created_at, u.last_sign_in_at,
           -- 어느 방법으로 로그인했는지(email / kakao / google / naver).
           coalesce(u.raw_app_meta_data->>'provider', 'email') as provider
    from auth.users u
    where q is null or q = '' or u.email ilike '%' || q || '%'
  ),
  counted as (select count(*) as total from base),
  page as (
    select * from base order by created_at desc limit page_size offset page_offset
  )
  select json_build_object(
    'total', (select total from counted),
    'rows', coalesce((
      select json_agg(row)
      from (
        select
          p.id, p.email, p.created_at, p.last_sign_in_at, p.provider,
          -- 속한 가족들(이름과 그 가족에서 쓰는 이름). 여러 가족일 수 있다.
          -- 초대 코드도 실어 보낸다: 이름이 같은 가족이 둘이면(테스트로 "우리집"을 두 번
          -- 만든 경우 등) 화면에서 이름만으로는 같은 가족이 두 번 나온 것처럼 보인다.
          coalesce((
            select json_agg(json_build_object('family_id', f.id, 'family_name', f.name,
                                              'display_name', fm.display_name, 'invite_code', f.invite_code)
                            order by fm.created_at)
            from public.family_members fm join public.families f on f.id = fm.family_id
            where fm.user_id = p.id
          ), '[]'::json) as families,
          (select count(*) from public.gifticons g where g.created_by = p.id) as uploaded,
          (select count(*) from public.gifticons g where g.used_by = p.id) as used,
          (select count(*) from public.push_subscriptions s where s.user_id = p.id) as push_devices,
          exists (select 1 from public.user_consents c where c.user_id = p.id) as agreed,
          exists (select 1 from public.admin_users a where a.user_id = p.id) as is_admin
        from page p
      ) row
    ), '[]'::json)
  );
$$;

-- 기프티콘 목록. status_filter는 unused | used | expired | hidden 중 하나(비우면 전부).
-- 화면에서 보는 '만료'는 status 컬럼이 아니라 유효기한으로 정해지므로 여기서 함께 계산한다.
create or replace function public.admin_list_gifticons(
  q text default null,
  status_filter text default null,
  family_filter uuid default null,
  page_size int default 50,
  page_offset int default 0
)
returns json
language sql
security definer
set search_path = public
stable
as $$
  with today as (select (now() at time zone 'Asia/Seoul')::date as d),
  base as (
    select g.id, g.name, g.brand, g.category, g.amount, g.owner,
           g.expires_at, g.used_at, g.used_by_name, g.claimed_by_name,
           g.created_at, g.hidden_at, g.family_id,
           f.name as family_name,
           case
             when g.status = 'used' then 'used'
             when g.expires_at is not null and g.expires_at < (select d from today) then 'expired'
             else 'unused'
           end as state
    from public.gifticons g
    left join public.families f on f.id = g.family_id
    where (q is null or q = ''
           or g.name ilike '%' || q || '%'
           or g.brand ilike '%' || q || '%'
           or g.owner ilike '%' || q || '%')
      and (family_filter is null or g.family_id = family_filter)
  ),
  filtered as (
    select * from base
    where status_filter is null or status_filter = ''
       or (status_filter = 'hidden' and hidden_at is not null)
       or (status_filter <> 'hidden' and state = status_filter and hidden_at is null)
  ),
  counted as (select count(*) as total, coalesce(sum(amount), 0) as amount_sum from filtered)
  select json_build_object(
    'total', (select total from counted),
    'amount_sum', (select amount_sum from counted),
    'rows', coalesce((
      select json_agg(row)
      from (select * from filtered order by created_at desc limit page_size offset page_offset) row
    ), '[]'::json)
  );
$$;

-- 가족 목록. 구성원과 기프티콘 현황을 한 줄에 모아 본다.
create or replace function public.admin_list_families(
  q text default null,
  page_size int default 50,
  page_offset int default 0
)
returns json
language sql
security definer
set search_path = public
stable
as $$
  with today as (select (now() at time zone 'Asia/Seoul')::date as d),
  base as (
    select f.id, f.name, f.invite_code, f.created_at
    from public.families f
    where q is null or q = '' or f.name ilike '%' || q || '%' or f.invite_code ilike '%' || q || '%'
  ),
  counted as (select count(*) as total from base),
  page as (select * from base order by created_at desc limit page_size offset page_offset)
  select json_build_object(
    'total', (select total from counted),
    'rows', coalesce((
      select json_agg(row)
      from (
        select
          p.id, p.name, p.invite_code, p.created_at,
          coalesce((
            select json_agg(fm.display_name order by fm.created_at)
            from public.family_members fm where fm.family_id = p.id
          ), '[]'::json) as members,
          (select count(*) from public.family_members fm where fm.family_id = p.id) as member_count,
          (select count(*) from public.gifticons g where g.family_id = p.id and g.hidden_at is null) as gifticons,
          (select count(*) from public.gifticons g
            where g.family_id = p.id and g.hidden_at is null and g.status <> 'used'
              and (g.expires_at is null or g.expires_at >= (select d from today))) as unused,
          (select coalesce(sum(g.amount), 0) from public.gifticons g
            where g.family_id = p.id and g.hidden_at is null) as amount_total,
          (select count(*) from public.family_join_requests r
            where r.family_id = p.id and r.status = 'pending') as pending_requests
        from page p
      ) row
    ), '[]'::json)
  );
$$;

-- ===================== 관리자 명단 고치기 =====================

-- 관리자 화면의 "회원 관리"에서 다른 사람을 관리자로 넣고 빼는 데 쓴다.
-- 넣고 빼는 판단 자체는 여기서 한다. 화면이나 함수 쪽에서 검사하면 두 사람이 동시에
-- 눌렀을 때 둘 다 통과해버릴 수 있는데, 여기서는 한 트랜잭션 안에서 세고 지우므로
-- 그 틈이 없다.
--
-- actor_id는 지금 누르고 있는 사람이다. 자기 자신을 빼는 것을 막는 데 쓴다.
create or replace function public.admin_set_admin(
  target_id uuid,
  make_admin boolean,
  actor_id uuid,
  memo_text text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  target_email text;
  remaining int;
begin
  select email into target_email from auth.users where id = target_id;
  if target_email is null then
    return json_build_object('ok', false, 'error', '그런 계정이 없어요.');
  end if;

  if make_admin then
    -- 이미 있으면 이메일만 최신으로 맞춘다(계정이 이메일을 바꿨을 수 있다).
    insert into public.admin_users (user_id, email, memo)
    values (target_id, target_email, coalesce(nullif(btrim(memo_text), ''), '관리자 화면에서 추가'))
    on conflict (user_id) do update set email = excluded.email;
    return json_build_object('ok', true, 'email', target_email);
  end if;

  -- 자기 자신은 뺄 수 없다. 실수로 스스로를 빼면 화면으로는 다시 들어올 길이 없고
  -- SQL 편집기를 열어야 한다.
  if target_id = actor_id then
    return json_build_object('ok', false, 'error', '자기 자신은 관리자에서 뺄 수 없어요.');
  end if;

  -- 마지막 한 명은 남긴다. 명단이 비면 아무도 관리자 화면에 못 들어온다.
  select count(*) into remaining from public.admin_users;
  if remaining <= 1 then
    return json_build_object('ok', false, 'error', '관리자가 한 명뿐이라 뺄 수 없어요.');
  end if;

  delete from public.admin_users where user_id = target_id;
  return json_build_object('ok', true, 'email', target_email);
end $$;

-- 목록도 통계와 같은 이유로 서버 전용이다.
do $$
declare
  fn text;
begin
  foreach fn in array array[
    'public.admin_list_users(text, int, int)',
    'public.admin_list_gifticons(text, text, uuid, int, int)',
    'public.admin_list_families(text, int, int)',
    'public.admin_set_admin(uuid, boolean, uuid, text)'
  ] loop
    execute format('revoke all on function %s from public', fn);
    execute format('revoke all on function %s from anon', fn);
    execute format('revoke all on function %s from authenticated', fn);
    execute format('grant execute on function %s to service_role', fn);
  end loop;
end $$;

-- ===================== 미아 사진 청소 =====================

-- 어느 기프티콘도 가리키지 않는 사진 파일을 찾는다. 지우지는 않는다 — 목록만 준다.
--
-- 왜 이런 파일이 생기나: 사진은 등록 버튼을 누르기 전에 미리 올라간다(그 몇 초를 아끼려고
-- 떼어놨다). 그러고 창을 닫으면 줄은 안 생기고 파일만 남는다. 기프티콘을 지울 때는 사진도
-- 같이 지우지만, 그 삭제만 실패한 경우도 남는다. 계정을 지울 때도 남의 기프티콘에 붙지
-- 않은 것은 주인 표시만 끊고 파일은 뒀다.
--
-- ── 이 함수에서 제일 중요한 건 "안 지우는 것" ──
--
-- 잘못 올라간 파일이 남는 것보다, 멀쩡한 기프티콘의 사진이 사라지는 쪽이 훨씬 나쁘다.
-- 되돌릴 방법이 없다. 그래서 세 가지를 건다.
--
--   1) 나이 제한. 갓 올라온 파일은 아직 등록 중일 수 있다. 최소 7일은 강제한다.
--   2) 세 칸을 전부 본다. 사진 경로는 image_paths(배열)·barcode_image_path·
--      thumb_image_path 세 군데에 나뉘어 있다. 한 칸이라도 빠뜨리면 그 종류가 통째로
--      미아로 보인다.
--   3) 안전 밸브. 가리키는 경로가 하나도 없는데 파일은 있다면, 그건 "다 미아"가 아니라
--      목록을 못 읽은 것이다. 그때는 답을 주지 않고 멈춘다.
create or replace function public.orphan_images(min_age_days int default 90)
returns table (
  path text,
  family_id uuid,
  family_name text,
  size_bytes bigint,
  uploaded_at timestamptz,
  age_days int,
  owner_gone boolean,
  reason text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  days int := greatest(coalesce(min_age_days, 90), 7);
  referenced_count bigint;
  object_count bigint;
begin
  select count(*) into object_count
  from storage.objects where bucket_id = 'gifticon-images';

  select count(*) into referenced_count
  from (
    select unnest(image_paths) as p from public.gifticons
    union
    select barcode_image_path from public.gifticons where barcode_image_path is not null
    union
    select thumb_image_path from public.gifticons where thumb_image_path is not null
  ) t
  where t.p is not null;

  if referenced_count = 0 and object_count > 0 then
    raise exception
      '안전장치가 걸렸어요: 기프티콘이 가리키는 사진이 한 장도 없는데 파일은 %개예요. 목록을 못 읽은 것일 수 있어 아무것도 알려주지 않습니다.',
      object_count;
  end if;

  return query
  with referenced as (
    select unnest(image_paths) as p from public.gifticons
    union
    select barcode_image_path from public.gifticons where barcode_image_path is not null
    union
    select thumb_image_path from public.gifticons where thumb_image_path is not null
  ),
  objs as (
    select
      o.name::text as p,
      -- 경로는 '<가족 id>/<시각>-<임의값>.jpg'로 만든다(client/src/api.js의 uploadOne).
      -- 형식이 다르면 가족을 못 붙이는 것뿐, 미아 판단에는 쓰지 않는다.
      case when split_part(o.name, '/', 1) ~ '^[0-9a-fA-F-]{36}$'
           then split_part(o.name, '/', 1)::uuid end as fam,
      coalesce((o.metadata->>'size')::bigint, 0) as bytes,
      o.created_at as made,
      o.owner as who
    from storage.objects o
    where o.bucket_id = 'gifticon-images'
      and o.created_at < now() - make_interval(days => days)
      and not exists (select 1 from referenced r where r.p = o.name)
  )
  select
    objs.p,
    objs.fam,
    f.name,
    objs.bytes,
    objs.made,
    extract(day from now() - objs.made)::int,
    (objs.who is null),
    case
      when objs.fam is null then '어느 기프티콘에도 안 적혀 있어요 · 경로에 가족이 없어요'
      when f.id is null then '어느 기프티콘에도 안 적혀 있어요 · 올린 가족이 없어졌어요'
      when objs.who is null then '어느 기프티콘에도 안 적혀 있어요 · 올린 사람이 탈퇴했어요'
      else '어느 기프티콘에도 안 적혀 있어요'
    end
  from objs
  left join public.families f on f.id = objs.fam
  order by objs.made;
end $$;

do $$
begin
  execute 'revoke all on function public.orphan_images(int) from public';
  execute 'revoke all on function public.orphan_images(int) from anon';
  execute 'revoke all on function public.orphan_images(int) from authenticated';
  execute 'grant execute on function public.orphan_images(int) to service_role';
end $$;
