-- 관리자 대시보드(admin/) 전용 통계. Supabase SQL editor에서 이 파일 내용을 그대로 실행하세요.
-- 여러 번 실행해도 안전합니다(idempotent). schema.sql과는 별개 파일인데, 앱이 돌아가는 데
-- 필요한 것과 관리자가 들여다보는 것을 섞지 않기 위해서다.
--
-- 여기 만드는 것들은 전부 서비스 롤(서버)만 쓸 수 있다. 대시보드는 주소만 알면 누구나
-- 열리는 정적 HTML이라, 브라우저가 직접 데이터베이스를 읽게 하면 통계 전체가 공개되는
-- 셈이다. 그래서 브라우저 → admin-stats Edge Function(로그인 + 관리자 명단 확인)
-- → 이 함수 순서로만 흐른다.

-- ===================== 관리자 명단 =====================

-- 관리자 대시보드에 들어올 수 있는 사람. 앱과 같은 계정으로 로그인하되, 여기 이름이
-- 올라 있는 사람만 통계를 본다.
--
-- 계정에 'is_admin' 같은 칸을 두지 않고 별도 표로 두는 이유: 관리자는 앱의 개념이 아니라
-- 운영의 개념이다. 앱 어디에서도 "내가 관리자인가"를 묻지 않으므로 앱 데이터에 섞을 이유가
-- 없고, 표를 따로 두면 이 파일 하나만 봐도 누가 들어올 수 있는지 한눈에 보인다.
--
-- 빼는 것도 한 줄이면 된다(delete). 예전 방식(공유 비밀 토큰)은 한 사람을 빼려면 토큰을
-- 바꾸고 함수를 다시 배포해야 했는데, 그러면 나머지 관리자도 전부 다시 설정해야 했다.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  -- 화면에 누구인지 보여주고, 나중에 명단을 볼 때 uuid만 늘어놓지 않으려고 함께 적어둔다.
  email text,
  memo text,
  created_at timestamptz not null default now()
);

-- 사용자가 직접 볼 일도 고칠 일도 없다. 정책을 하나도 만들지 않아서
-- (RLS는 켜져 있고 정책이 없으면 아무것도 통과하지 못한다) 서버만 다룬다.
-- 특히 "내가 관리자인지" 조차 앱에서 물어볼 수 없어야 한다. 명단이 읽히면 누구를 노려야
-- 하는지 알려주는 셈이기 때문이다.
alter table public.admin_users enable row level security;

-- ⚠️ 첫 관리자는 여기서 직접 넣어야 한다. 아래 이메일을 본인 것으로 바꿔 한 번 실행하세요.
--    (앱에 한 번이라도 로그인한 계정이어야 auth.users에 있어서 등록됩니다.)
--
--    insert into public.admin_users (user_id, email, memo)
--    select id, email, '최초 관리자' from auth.users where email = '여기에@본인이메일.com'
--    on conflict (user_id) do nothing;
--
-- 나중에 관리자를 빼려면:
--    delete from public.admin_users where email = '뺄사람@이메일.com';
--
-- 지금 명단을 보려면:
--    select email, memo, created_at from public.admin_users order by created_at;

-- ===================== AI 호출 기록 =====================

-- api_usage_total은 "몇 번 불렀나"만 세서 요금을 어림잡을 수밖에 없다. AI 요금은 실제로는
-- 토큰 수로 매겨지므로, 호출마다 모델과 토큰 수를 적어두면 비용을 어림이 아니라 계산으로
-- 알 수 있다. 기록은 Edge Function(analyze-gifticon, search-price)이 응답을 받은 뒤 남긴다.
create table if not exists public.ai_usage_log (
  id bigint generated by default as identity primary key,
  action text not null,              -- analyze | price
  model text not null,               -- claude-haiku-4-5 등
  input_tokens int not null default 0,
  output_tokens int not null default 0,
  -- 가격 검색은 웹 검색 도구를 쓰는데, 검색 1회마다 토큰과 별도의 요금이 붙는다($10/1,000회).
  web_search_requests int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_log_created_at_idx on public.ai_usage_log (created_at);

-- 사용자가 직접 볼 일도 고칠 일도 없다. 정책을 하나도 만들지 않아서
-- (RLS는 켜져 있고 정책이 없으면 아무것도 통과하지 못한다) 서버만 다룬다.
alter table public.ai_usage_log enable row level security;

-- ===================== 통계 함수 =====================

-- 대시보드가 그리는 모든 숫자를 한 번에 돌려준다. 화면에서 쿼리를 여러 번 나눠 부르면
-- 부를 때마다 권한을 따져야 하고, 숫자끼리 시점이 어긋난다(집계 도중 데이터가 바뀌면
-- 카드마다 다른 순간을 보게 된다). 한 함수에서 다 세면 둘 다 해결된다.
--
-- 날짜 묶음 기준: 앱 데이터(가입, 등록, 사용)는 한국 시간(Asia/Seoul) 날짜로 묶는다.
-- 관리자가 한국에서 보는 화면이라 "오늘"이 한국의 오늘이어야 자연스럽다.
-- 단 api_usage_total의 day 컬럼은 bump_api_usage가 UTC 날짜로 적으므로 그대로 둔다
-- (다시 묶을 원본 시각이 없다). 하루 경계가 9시간 어긋날 수 있다는 뜻인데,
-- 호출량 추이를 보는 데는 지장이 없다.
create or replace function public.admin_dashboard_stats()
returns json
language sql
security definer
set search_path = public
stable
as $$
  with kst as (
    select (now() at time zone 'Asia/Seoul')::date as today
  ),

  -- ---------- 사용자 ----------
  users_by_month as (
    select to_char(created_at at time zone 'Asia/Seoul', 'YYYY-MM') as month, count(*) as count
    from auth.users
    group by 1 order by 1
  ),
  users_by_day as (
    select (created_at at time zone 'Asia/Seoul')::date as day, count(*) as count
    from auth.users
    where created_at >= now() - interval '180 days'
    group by 1 order by 1
  ),

  -- ---------- 기프티콘 ----------
  -- hidden_at이 있는 것(가족을 나간 사람 것)은 앱 화면에는 안 보이지만, "지금까지 업로드된
  -- 수"에는 포함해서 센다. 대신 hidden 수를 따로 알려줘서 구분할 수 있게 한다.
  g as (
    select
      count(*) as total,
      count(*) filter (where hidden_at is not null) as hidden,
      count(*) filter (where status = 'used') as used,
      count(*) filter (where status <> 'used' and expires_at is not null
                       and expires_at < (select today from kst)) as expired,
      count(*) filter (where status <> 'used' and (expires_at is null
                       or expires_at >= (select today from kst))) as unused,
      coalesce(sum(amount), 0) as amount_total,
      coalesce(sum(amount) filter (where status = 'used'), 0) as amount_used,
      coalesce(sum(amount) filter (where status <> 'used' and expires_at is not null
                                   and expires_at < (select today from kst)), 0) as amount_expired,
      coalesce(sum(amount) filter (where status <> 'used' and (expires_at is null
                                   or expires_at >= (select today from kst))), 0) as amount_unused,
      count(*) filter (where amount is null) as no_amount
    from public.gifticons
  ),
  g_by_day as (
    select (created_at at time zone 'Asia/Seoul')::date as day,
           count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    where created_at >= now() - interval '180 days'
    group by 1 order by 1
  ),
  g_by_month as (
    select to_char(created_at at time zone 'Asia/Seoul', 'YYYY-MM') as month,
           count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    group by 1 order by 1
  ),
  g_used_by_day as (
    select used_at as day, count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    where status = 'used' and used_at is not null and used_at >= (select today from kst) - 180
    group by 1 order by 1
  ),
  g_used_by_month as (
    select to_char(used_at, 'YYYY-MM') as month, count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    where status = 'used' and used_at is not null
    group by 1 order by 1
  ),
  g_categories as (
    select category, count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    group by 1 order by count(*) desc
  ),
  g_brands as (
    select coalesce(nullif(btrim(brand), ''), '(브랜드 없음)') as brand,
           count(*) as count, coalesce(sum(amount), 0) as amount
    from public.gifticons
    group by 1 order by count(*) desc
    limit 10
  ),
  -- 등록에서 사용까지 걸린 평균 일수. 관리 지표라기보다 "가족들이 실제로 잘 꺼내 쓰는가"를
  -- 보여주는 숫자다. used_at은 날짜만 있어서 등록 시각도 한국 날짜로 맞춰 뺀다.
  g_avg_use as (
    select round(avg(used_at - (created_at at time zone 'Asia/Seoul')::date), 1) as days
    from public.gifticons
    where status = 'used' and used_at is not null
  ),

  -- ---------- 가족 ----------
  f as (
    select
      (select count(*) from public.families) as families,
      (select count(*) from public.family_members) as members
  ),
  f_sizes as (
    select size, count(*) as families
    from (select count(*) as size from public.family_members group by family_id) t
    group by 1 order by 1
  ),
  f_by_month as (
    select to_char(created_at at time zone 'Asia/Seoul', 'YYYY-MM') as month, count(*) as count
    from public.families
    group by 1 order by 1
  ),

  -- ---------- 활동/기타 ----------
  etc as (
    select
      (select count(*) from public.push_subscriptions) as push_subscriptions,
      (select count(*) from public.family_join_requests where status = 'pending') as pending_join_requests,
      (select count(*) from public.gifticons
        where status <> 'used' and expires_at is not null
          and expires_at >= (select today from kst)
          and expires_at < (select today from kst) + 7) as expiring_7d,
      (select count(*) from public.gifticons
        where status <> 'used' and expires_at is not null
          and expires_at >= (select today from kst)
          and expires_at < (select today from kst) + 30) as expiring_30d
  ),
  -- 그날 돈 나가는 기능을 한 번이라도 쓴 사람 수. 정확한 DAU는 아니지만(그냥 열어보기만 한
  -- 사람은 안 잡힌다) 별도 로그 없이 활동 추이를 볼 수 있는 가장 가까운 숫자다.
  active_by_day as (
    select day, count(distinct user_id) as users
    from public.api_usage
    group by 1 order by 1
  ),

  -- ---------- API / AI 호출 ----------
  api_daily as (
    select action, day, count from public.api_usage_total order by day, action
  ),
  ai_daily as (
    select (created_at at time zone 'Asia/Seoul')::date as day, action, model,
           count(*) as calls,
           sum(input_tokens) as input_tokens,
           sum(output_tokens) as output_tokens,
           sum(web_search_requests) as web_search_requests
    from public.ai_usage_log
    group by 1, 2, 3 order by 1
  )

  select json_build_object(
    'generated_at', now(),
    'users', json_build_object(
      'total', (select count(*) from auth.users),
      'by_day', (select coalesce(json_agg(u), '[]'::json) from users_by_day u),
      'by_month', (select coalesce(json_agg(u), '[]'::json) from users_by_month u)
    ),
    'families', json_build_object(
      'total', (select families from f),
      'members', (select members from f),
      'size_distribution', (select coalesce(json_agg(s), '[]'::json) from f_sizes s),
      'by_month', (select coalesce(json_agg(m), '[]'::json) from f_by_month m)
    ),
    'gifticons', json_build_object(
      'total', (select total from g),
      'unused', (select unused from g),
      'used', (select used from g),
      'expired', (select expired from g),
      'hidden', (select hidden from g),
      'no_amount', (select no_amount from g),
      'amount_total', (select amount_total from g),
      'amount_unused', (select amount_unused from g),
      'amount_used', (select amount_used from g),
      'amount_expired', (select amount_expired from g),
      'avg_days_to_use', (select days from g_avg_use),
      'by_day', (select coalesce(json_agg(d), '[]'::json) from g_by_day d),
      'by_month', (select coalesce(json_agg(m), '[]'::json) from g_by_month m),
      'used_by_day', (select coalesce(json_agg(d), '[]'::json) from g_used_by_day d),
      'used_by_month', (select coalesce(json_agg(m), '[]'::json) from g_used_by_month m),
      'categories', (select coalesce(json_agg(c), '[]'::json) from g_categories c),
      'brands', (select coalesce(json_agg(b), '[]'::json) from g_brands b)
    ),
    'engagement', json_build_object(
      'push_subscriptions', (select push_subscriptions from etc),
      'pending_join_requests', (select pending_join_requests from etc),
      'expiring_7d', (select expiring_7d from etc),
      'expiring_30d', (select expiring_30d from etc),
      'active_by_day', (select coalesce(json_agg(a), '[]'::json) from active_by_day a)
    ),
    'api_usage_daily', (select coalesce(json_agg(a), '[]'::json) from api_daily a),
    'ai_usage_daily', (select coalesce(json_agg(a), '[]'::json) from ai_daily a)
  );
$$;

-- 이 함수는 auth.users까지 읽는다(security definer). 브라우저에서 부를 수 있으면
-- 로그인한 아무나 전체 통계를 보게 되므로, 서버(Edge Function의 서비스 롤)만 부른다.
revoke all on function public.admin_dashboard_stats() from public;
revoke all on function public.admin_dashboard_stats() from anon;
revoke all on function public.admin_dashboard_stats() from authenticated;
grant execute on function public.admin_dashboard_stats() to service_role;
