-- 쓴 사건을 한 줄씩 남긴다
--
-- 지금까지는 기프티콘 한 장이 곧 사용 내역 한 줄이었다. 5만원권을 엄마 3,000 · 딸 20,000 ·
-- 아들 1,500 · 마지막 25,500으로 나눠 써도, 앱이 아는 것은 "쓴 금액 50,000" 하나뿐이라
-- 마지막에 다 채운 사람이 5만원을 쓴 것으로 보였다. 앞의 세 번은 화면 어디에도 없었다.
--
-- 같은 원인으로 사용취소도 안 됐다. 마지막 한 번만 되돌리려 해도 그게 얼마였는지를
-- 모른다. 합계 안에서 이미 뭉개졌기 때문이다.
--
-- 그래서 쓸 때마다 한 줄씩 적어둔다. 사용 내역 · 누가 썼나요 · 사용취소가 다 이 표를 본다.
--
-- ── 실행 순서 ─────────────────────────────────────────────────────────
-- supabase/schema.sql 을 먼저 돌린 뒤 이 파일을 돌린다. 여러 번 돌려도 안전하다.
-- 돌린 뒤에는 앱 쪽 배포도 함께 나가야 한다(사용 내역이 이 표를 읽는다).

-- ────────────────────────────────────────────────────────────────────
-- 1. 표
-- ────────────────────────────────────────────────────────────────────

create table if not exists public.gifticon_uses (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,

  -- 기프티콘을 지우면 그 기록도 같이 지운다.
  --
  -- 알림(activities)은 반대로 남겨두는데, 거기는 "무슨 일이 있었나"를 적는 자리라
  -- 지운 일도 일어난 일이다. 이 표는 "지금 우리 가족이 쓴 것들"을 세는 자리라,
  -- 목록에서 지운 것이 결산에는 남아 있으면 숫자가 안 맞는다.
  gifticon_id bigint not null references public.gifticons(id) on delete cascade,

  -- 이름과 썸네일을 여기에도 적어둔다. 목록을 그릴 때마다 기프티콘 표를 다시 붙일
  -- 일이 없고, 나중에 상품명을 고쳐도 그때 쓴 이름이 그대로 남는다.
  gifticon_name text not null,
  thumb_image_path text,

  -- 쓴 사람. 이름을 따로 적는 이유는 used_by_name과 같다 — 그 사람이 가족에서 나가거나
  -- 계정을 지워도 "누가 썼는지"는 남아 있어야 한다.
  user_id uuid references auth.users(id) on delete set null,
  user_name text not null,

  -- 이번에 쓴 금액. 금액권이면 그때 깎은 만큼, 보통 기프티콘이면 액면가.
  -- 금액을 모르는 기프티콘도 있어서 비어 있을 수 있다.
  amount integer,

  used_at date not null default (now() at time zone 'Asia/Seoul')::date,
  created_at timestamptz not null default now()
);

create index if not exists gifticon_uses_family_idx
  on public.gifticon_uses (family_id, used_at desc, created_at desc);
create index if not exists gifticon_uses_gifticon_idx
  on public.gifticon_uses (gifticon_id, created_at desc);

alter table public.gifticon_uses enable row level security;

-- 우리 가족 것만 본다. 쓰기 정책은 두지 않는다 — 아래 트리거와 함수(security definer)만
-- 적는다. 브라우저에서 직접 넣을 수 있으면 있지도 않은 사용을 지어낼 수 있다.
drop policy if exists "gifticon_uses select family" on public.gifticon_uses;
create policy "gifticon_uses select family" on public.gifticon_uses
  for select to authenticated
  using (public.is_family_member(family_id));

-- ────────────────────────────────────────────────────────────────────
-- 2. 쓸 때마다 한 줄 적는다
-- ────────────────────────────────────────────────────────────────────
--
-- 알림을 남기는 트리거를 그대로 늘린다. 기록을 남기는 곳이 하나여야 나중에 다른 경로가
-- 생겨도(관리자 화면, 일괄 처리) 빠뜨리지 않는다.
--
-- 알림과 다른 점이 하나 있다. 알림은 목데이터를 걸러내는데(사람이 올린 것이 아니라
-- 앱이 채워 넣은 것이라 알릴 일이 아니다), 이 표는 걸러내지 않는다. 목데이터로도 사용
-- 내역 화면이 돌아야 확인할 수 있어서다.

create or replace function public.log_gifticon_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  what text;
  who text;
  spent integer := null;
begin
  if TG_OP = 'INSERT' then
    what := 'created';
  elsif new.status is distinct from old.status then
    what := case when new.status = 'used' then 'used' else 'unused' end;
    -- 금액권을 마지막 한 번에 다 써서 사용완료로 넘어간 경우, 그 마지막 금액도 함께 적는다.
    if new.spent_amount > coalesce(old.spent_amount, 0) then
      spent := new.spent_amount - coalesce(old.spent_amount, 0);
    end if;
  elsif new.spent_amount > coalesce(old.spent_amount, 0) then
    -- 금액권을 조금 썼다. 아직 잔액이 남아서 상태는 그대로다.
    what := 'spent';
    spent := new.spent_amount - coalesce(old.spent_amount, 0);
  else
    -- 이름이나 금액만 고친 것은 알릴 일이 아니다. 쓴 금액이 줄어든 것(사용취소)도
    -- 여기로 온다 — 아래 undo_last_use가 이미 줄을 지웠으므로 할 일이 없다.
    return new;
  end if;

  select display_name into who
  from public.family_members
  where family_id = new.family_id and user_id = auth.uid();

  -- 쓴 사건 한 줄.
  --
  -- 금액은 금액권이면 이번에 깎은 만큼(spent), 보통 기프티콘이면 액면가다. 금액권을
  -- 조금씩 쓰지 않고 곧장 사용완료로 넘긴 경우도 액면가로 잡힌다 — 그건 "다 썼다"는 뜻이다.
  if what in ('used', 'spent') and new.family_id is not null then
    insert into public.gifticon_uses (
      family_id, gifticon_id, gifticon_name, thumb_image_path,
      user_id, user_name, amount, used_at
    )
    values (
      new.family_id, new.id, new.name, new.thumb_image_path,
      auth.uid(),
      coalesce(who, new.used_by_name, new.owner, '알 수 없음'),
      coalesce(spent, nullif(new.amount, 0)),
      coalesce(new.used_at, (now() at time zone 'Asia/Seoul')::date)
    );
  end if;

  -- ⚠️ 테스트 전용. 출시 전에 이 두 줄을 지운다(client/src/sampleData.js와 함께).
  -- 목데이터는 사람이 올린 것이 아니라 앱이 채워 넣은 것이라 알릴 일이 아니다.
  if new.code like '9000111122%' then
    return new;
  end if;

  -- 가족에서 나간 사람의 기프티콘은 목록에 안 보이므로 알릴 것도 없다.
  if new.family_id is null or new.hidden_at is not null then
    return new;
  end if;

  insert into public.activities (family_id, kind, actor_id, actor_name, gifticon_id, gifticon_name, amount)
  values (new.family_id, what, auth.uid(), coalesce(who, new.used_by_name, new.owner), new.id, new.name, spent);

  return new;
end;
$$;

drop trigger if exists gifticons_activity on public.gifticons;
create trigger gifticons_activity
  after insert or update of status, spent_amount on public.gifticons
  for each row execute function public.log_gifticon_activity();

-- ────────────────────────────────────────────────────────────────────
-- 3. 사용취소 — 마지막 한 번만 되돌린다
-- ────────────────────────────────────────────────────────────────────
--
-- 5만원권을 셋이 나눠 쓰고 내가 마지막 25,500원을 채웠다면, 사용취소는 그 25,500원만
-- 되돌린다. 엄마 3,000 · 딸 20,000은 그대로 남는다.
--
-- 전부 되돌리는 쪽으로 하지 않은 이유: 사용취소를 누르는 상황은 대개 "방금 잘못 눌렀다"인데,
-- 전부 되돌리면 딸이 진짜로 쓴 2만원까지 없던 일이 된다. 남의 기록을 지우면 안 된다.
--
-- 보통 기프티콘에는 이 구분이 없다. 한 번 쓰면 끝이라 마지막 한 번이 곧 전부다.
--
-- 화면이 아니라 여기서 하는 이유는 세 가지가 한꺼번에 일어나야 해서다 — 줄 지우기,
-- 쓴 금액 되돌리기, 상태 바꾸기. 화면에서 나눠 보내면 중간에 끊겼을 때 어긋난 채로 남는다.

create or replace function public.undo_last_use(gid bigint)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  g public.gifticons;
  last_use public.gifticon_uses;
  back integer := 0;
begin
  select * into g from public.gifticons where id = gid;
  if not found then
    raise exception '기프티콘을 찾을 수 없어요.';
  end if;
  -- security definer라 RLS를 지나간다. 남의 가족 것을 되돌리지 못하게 여기서 막는다.
  if g.family_id is null or not public.is_family_member(g.family_id) then
    raise exception '우리 가족의 기프티콘이 아니에요.';
  end if;

  select * into last_use
  from public.gifticon_uses
  where gifticon_id = gid
  order by created_at desc, id desc
  limit 1;

  if found then
    back := coalesce(last_use.amount, 0);
    delete from public.gifticon_uses where id = last_use.id;
  end if;

  -- 0 아래로 내려가지 않게 막는다. 이 표가 생기기 전에 쓴 것들은 되돌릴 줄이 없어서
  -- back이 0인데, 그때는 쓴 금액을 그대로 두고 상태만 되돌린다.
  update public.gifticons
  set status = 'unused',
      spent_amount = greatest(0, spent_amount - back),
      used_at = null,
      used_by = null,
      used_by_name = null,
      updated_at = now()
  where id = gid;

  return json_build_object('ok', true, 'restored', back);
end;
$$;

revoke all on function public.undo_last_use(bigint) from public;
revoke all on function public.undo_last_use(bigint) from anon;
grant execute on function public.undo_last_use(bigint) to authenticated;

-- ────────────────────────────────────────────────────────────────────
-- 4. 지금까지 쓴 것들을 옮긴다
-- ────────────────────────────────────────────────────────────────────
--
-- 이미 사용완료인 기프티콘마다 한 줄씩 만든다. 이걸 안 하면 이 표로 갈아타는 순간
-- 사용 내역이 텅 빈다. not exists로 걸러서 여러 번 돌려도 줄이 겹치지 않는다.
--
-- 아직 다 안 쓴 금액권(잔액이 남은 것)은 옮기지 않는다. 그동안 누가 얼마를 썼는지는
-- 어디에도 안 적혀 있어서, 한 사람에게 몰아주면 없는 사실을 지어내는 셈이 된다.
-- 그런 것들은 잔액은 맞고 내역만 비어 있다. 앞으로 쓰는 것부터 한 줄씩 쌓인다.

insert into public.gifticon_uses (
  family_id, gifticon_id, gifticon_name, thumb_image_path,
  user_id, user_name, amount, used_at, created_at
)
select
  g.family_id,
  g.id,
  g.name,
  g.thumb_image_path,
  g.used_by,
  coalesce(g.used_by_name, g.owner, '알 수 없음'),
  nullif(coalesce(nullif(g.spent_amount, 0), g.amount), 0),
  coalesce(g.used_at, (g.updated_at at time zone 'Asia/Seoul')::date),
  g.updated_at
from public.gifticons g
where g.status = 'used'
  and g.family_id is not null
  and not exists (select 1 from public.gifticon_uses u where u.gifticon_id = g.id);
