-- Supabase SQL editor에서 이 파일 내용을 그대로 실행하세요. 여러 번 실행해도 안전합니다(idempotent).
-- 로그인(이메일 매직링크) + 가족 그룹 공유를 지원합니다. 기프티콘은 family_id로 스코핑되고,
-- RLS(Row Level Security)로 "내가 속한 가족의 데이터만" 보이도록 강제합니다.

create extension if not exists pgcrypto;

create table if not exists public.gifticons (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default '기타',
  brand text,
  amount integer,
  owner text,
  code text,
  code_type text,
  expires_at date,
  memo text,
  image_paths text[] not null default '{}',
  status text not null default 'unused',
  used_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 예전에 이 파일을 이미 실행해서 image_path(단일) 컬럼이 있는 테이블이라면
-- 여러 장 업로드를 지원하는 image_paths(배열) 컬럼으로 옮겨준다.
alter table public.gifticons add column if not exists image_paths text[] not null default '{}';

-- 바코드 보기에서 원본 사진 대신 보여줄, 바코드/숫자 부분만 잘라낸 이미지
alter table public.gifticons add column if not exists barcode_image_path text;

-- 목록 썸네일로 쓸, 캡처에서 상품 사진 부분만 잘라낸 이미지.
-- 올리는 사진은 대개 카톡 선물함 화면을 통째로 찍은 캡처라, 그대로 줄이면 글자와 버튼까지
-- 뭉개져 들어가 무슨 상품인지 알아볼 수 없다. 상품 사진만 잘라 따로 둔다.
alter table public.gifticons add column if not exists thumb_image_path text;

-- 누가 등록했고 누가 썼는지. used_by_name은 사용한 사람의 이름을 그대로 적어두는 칸인데,
-- 나중에 그 사람이 가족에서 나가도 사용 내역에 이름이 남아야 하기 때문에 따로 둔다.
alter table public.gifticons add column if not exists created_by uuid references auth.users(id);
alter table public.gifticons add column if not exists used_by uuid references auth.users(id);
alter table public.gifticons add column if not exists used_by_name text;

-- 가족에서 나간 사람의 기프티콘을 감추는 표시. 지우지는 않고 목록에서만 빼둔다.
alter table public.gifticons add column if not exists hidden_at timestamptz;

-- 금액권(3만원권처럼 값이 적힌 상품권)인지, 그리고 지금까지 얼마를 썼는지.
--
-- 금액권은 한 번에 다 쓰지 않는다. 3만원권으로 1만 2천원을 썼으면 아직 1만 8천원이
-- 남아 있는데, 사용/미사용 두 칸만으로는 이걸 담을 데가 없었다. 다 썼다고 하면 남은
-- 돈이 사라지고, 안 썼다고 하면 얼마가 남았는지 아무도 모른다.
--
-- 그래서 "쓴 금액"을 따로 센다. amount(액면가)에서 이만큼을 뺀 것이 잔액이고,
-- 잔액이 0이 되는 순간에만 status가 used로 넘어간다.
alter table public.gifticons add column if not exists is_voucher boolean not null default false;
alter table public.gifticons add column if not exists spent_amount integer not null default 0;

-- 메모를 마지막으로 쓴 사람과 시각. 메모는 가족 누구나 고칠 수 있어서, 등록자 이름을
-- 붙여두면 다른 사람이 고쳤을 때 "태수님의 메모"인데 지연이 쓴 글이 되어버린다.
-- 이름을 그대로 적어두는 이유는 used_by_name과 같다. 그 사람이 가족에서 나가도
-- "누가 남긴 말인지"는 남아 있어야 한다.
alter table public.gifticons add column if not exists memo_by uuid references auth.users(id);
alter table public.gifticons add column if not exists memo_by_name text;
alter table public.gifticons add column if not exists memo_at timestamptz;

-- 이 컬럼이 생기기 전에 이미 "사용 완료"로 표시된 것들은 사용한 사람을 알 수 없으니,
-- 받은 사람 이름으로 채워둔다.
update public.gifticons set used_by_name = owner where status = 'used' and used_by_name is null;

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'gifticons' and column_name = 'image_path') then
    update public.gifticons
      set image_paths = array[image_path]
      where image_path is not null and (image_paths is null or array_length(image_paths, 1) is null);
    alter table public.gifticons drop column image_path;
  end if;
end $$;

-- ===================== 가족 그룹 (families / family_members) =====================

create table if not exists public.families (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  invite_code text not null unique,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.family_members (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now(),
  unique (family_id, user_id)
);

-- 기프티콘을 어느 가족 소유로 볼지 표시하는 컬럼
alter table public.gifticons add column if not exists family_id uuid references public.families(id);

-- 카드에 붙는 이름표 색(0부터 시작하는 팔레트 번호). 예전에는 화면에서 "가족 목록의 몇 번째
-- 사람인가"로 색을 정했는데, 누가 빠지면 남은 사람들 색이 통째로 밀리는 문제가 있었다.
-- 그래서 가족에 들어오는 시점에 번호를 받아 두고, 그 뒤로는 바뀌지 않게 한다.
alter table public.family_members add column if not exists tag_color smallint;

-- 이미 있는 멤버는 지금까지 화면에 보이던 색(가입 순서)을 그대로 굳혀서 채운다.
with numbered as (
  select id, (row_number() over (partition by family_id order by created_at) - 1) as idx
  from public.family_members
  where tag_color is null
)
update public.family_members fm
set tag_color = numbered.idx
from numbered
where fm.id = numbered.id;

-- 그 가족에서 아직 안 쓴 가장 작은 색 번호. 여섯 색을 다 쓰면 처음(0)부터 다시 돌려쓴다.
-- 색 개수는 화면 쪽 팔레트(client/src/components/GifticonCard.jsx)와 맞춰야 한다.
create or replace function public.next_tag_color(fid uuid)
returns smallint
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(min(candidate), 0)::smallint
  from generate_series(0, 5) as candidate
  where candidate not in (
    select coalesce(tag_color, -1) from public.family_members where family_id = fid
  );
$$;

-- 내가 이 family에 속해 있는지 확인하는 헬퍼 함수.
-- security definer라서 family_members 자체에 RLS가 걸려 있어도(재귀 없이) 안전하게 조회한다.
create or replace function public.is_family_member(fid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.family_members fm
    where fm.family_id = fid and fm.user_id = auth.uid()
  );
$$;

-- 가족 생성: families row + 만든 사람을 첫 멤버로 등록. 초대 코드는 6자리로 자동 생성.
create or replace function public.create_family(family_name text, member_name text)
returns public.families
language plpgsql
security definer
set search_path = public
as $$
declare
  new_family public.families;
  code text;
  attempt int := 0;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요해요.';
  end if;

  loop
    code := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));
    begin
      insert into public.families (name, invite_code, created_by)
      values (family_name, code, auth.uid())
      returning * into new_family;
      exit;
    exception when unique_violation then
      attempt := attempt + 1;
      if attempt > 5 then
        raise exception '초대 코드 생성에 실패했어요. 다시 시도해주세요.';
      end if;
    end;
  end loop;

  -- 가족을 만든 사람이 첫 멤버라 이름표 색은 항상 0번.
  insert into public.family_members (family_id, user_id, display_name, tag_color)
  values (new_family.id, auth.uid(), member_name, 0);

  return new_family;
end;
$$;

-- 초대 코드로 가족에 들어오는 일은 request_join_family()(승인 필요)로만 한다.
--
-- 예전의 join_family()는 코드만 맞으면 승인 없이 바로 넣어줬다. 화면에서 부르지 않게 고쳐도
-- 함수가 데이터베이스에 남아 있으면 소용이 없다. 로그인만 했으면 누구나 REST로 직접
-- (POST /rest/v1/rpc/join_family) 부를 수 있어서, 코드를 아는 사람은 승인 절차를 통째로
-- 건너뛸 수 있다. 그래서 함수 자체를 지운다. 인자 조합이 다른 옛 버전이 남아 있을 수도 있어
-- 이름이 같은 것을 모두 지운다.
--
-- 파일 앞쪽에서 지우는 이유: 뒤에서 오류가 나 스크립트가 중간에 멈추더라도, 우회로만은
-- 확실히 막혀 있어야 하기 때문이다.
do $$
declare
  victim record;
begin
  for victim in
    select p.oid::regprocedure as sig
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'join_family'
  loop
    execute format('drop function if exists %s', victim.sig);
  end loop;
end $$;

-- 가족에서 나가기. 내가 등록했거나 내 앞으로 되어 있는 기프티콘은 남은 가족에게 안 보이도록
-- 감춘 뒤(지우지는 않는다) 구성원 목록에서 빠진다. 다시 초대 코드로 들어올 수는 있지만,
-- 감춘 기프티콘이 저절로 되살아나지는 않는다.
--
-- 마지막 한 사람이 나가면 그 가족은 통째로 지운다. 빈 가족을 남겨두면 아무도 볼 수 없는
-- 기프티콘만 쌓이고, 초대 코드는 그대로 살아 있는데 승인해줄 사람이 없어서 그 코드를 아는
-- 사람은 누구나 승인 없이 들어와진다(request_join_family의 "구성원 0명" 예외).
--
-- 지워진 기프티콘의 사진 파일 경로를 돌려준다. 스토리지 파일은 SQL에서 지울 수 없어서
-- 부른 쪽이 이어서 지운다.
-- 예전에는 아무것도 돌려주지 않던 함수라, 돌려주는 값이 생긴 지금은 지웠다 다시 만들어야 한다
-- (create or replace로는 반환 타입을 바꿀 수 없다).
drop function if exists public.leave_family(uuid);
create or replace function public.leave_family(fid uuid)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  my_name text;
  orphan_paths text[] := '{}';
  family_deleted boolean := false;
begin
  select display_name into my_name
  from public.family_members
  where family_id = fid and user_id = auth.uid();

  if my_name is null then
    raise exception '이 가족의 구성원이 아니에요.';
  end if;

  delete from public.family_members where family_id = fid and user_id = auth.uid();

  if exists (select 1 from public.family_members where family_id = fid) then
    update public.gifticons
    set hidden_at = now()
    where family_id = fid
      and hidden_at is null
      and (created_by = auth.uid() or owner = my_name);

    -- 내가 찜해둔 것은 풀어준다. 나간 사람이 쓰러 갈 리 없는데 표시만 남아 있으면
    -- 남은 가족이 "저건 누가 쓰기로 했나 보다" 하고 계속 비켜 간다.
    update public.gifticons
    set claimed_by = null, claimed_by_name = null, claimed_at = null
    where family_id = fid and claimed_by = auth.uid();
  else
    select coalesce(array_agg(p), '{}') into orphan_paths
    from (
      select unnest(image_paths) as p from public.gifticons where family_id = fid
      union all
      select barcode_image_path from public.gifticons where family_id = fid and barcode_image_path is not null
    ) t;

    delete from public.gifticons where family_id = fid;
    -- family_members / family_join_requests / push_subscriptions는 따라서 지워진다.
    delete from public.families where id = fid;
    family_deleted := true;
  end if;

  return json_build_object('family_deleted', family_deleted, 'image_paths', orphan_paths);
end;
$$;

-- 내 이름 바꾸기. 기프티콘의 "받은 사람"과 사용 내역에는 이름이 글자 그대로 적혀 있어서,
-- 구성원 이름만 바꾸면 예전 기록이 남남처럼 떨어져 나간다(카드의 이름표 색도 안 맞게 된다).
-- 그래서 이 가족 안에 남아 있는 내 이름들을 같이 옮겨준다.
create or replace function public.rename_member(fid uuid, new_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := btrim(new_name);
  old_name text;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요해요.';
  end if;
  if clean_name = '' then
    raise exception '이름을 입력해주세요.';
  end if;
  if char_length(clean_name) > 20 then
    raise exception '이름은 20자까지 쓸 수 있어요.';
  end if;

  select display_name into old_name
  from public.family_members
  where family_id = fid and user_id = auth.uid();

  if old_name is null then
    raise exception '이 가족의 구성원이 아니에요.';
  end if;
  if old_name = clean_name then
    return;
  end if;

  -- 같은 이름이 둘이면 "받은 사람"이 누구인지 구분할 수 없다.
  if exists (
    select 1 from public.family_members
    where family_id = fid and user_id <> auth.uid() and display_name = clean_name
  ) then
    raise exception '가족 중에 같은 이름을 쓰는 사람이 있어요.';
  end if;

  update public.family_members
  set display_name = clean_name
  where family_id = fid and user_id = auth.uid();

  update public.gifticons
  set owner = clean_name
  where family_id = fid and owner = old_name;

  update public.gifticons
  set used_by_name = clean_name
  where family_id = fid and used_by = auth.uid();
end;
$$;

-- 가족 이름 바꾸기. 가족 안에서는 서로 같은 권한이라 구성원이면 누구나 바꿀 수 있다.
create or replace function public.rename_family(fid uuid, new_name text)
returns public.families
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text := btrim(new_name);
  updated public.families;
begin
  if not public.is_family_member(fid) then
    raise exception '이 가족의 구성원이 아니에요.';
  end if;
  if clean_name = '' then
    raise exception '가족 이름을 입력해주세요.';
  end if;
  if char_length(clean_name) > 20 then
    raise exception '가족 이름은 20자까지 쓸 수 있어요.';
  end if;

  update public.families set name = clean_name where id = fid returning * into updated;
  return updated;
end;
$$;

grant execute on function public.create_family(text, text) to authenticated;
grant execute on function public.leave_family(uuid) to authenticated;
grant execute on function public.rename_member(uuid, text) to authenticated;
grant execute on function public.rename_family(uuid, text) to authenticated;

alter table public.families enable row level security;
alter table public.family_members enable row level security;
alter table public.gifticons enable row level security;

drop policy if exists "families select own" on public.families;
create policy "families select own" on public.families
  for select to authenticated
  using (public.is_family_member(id));

drop policy if exists "family_members select own family" on public.family_members;
create policy "family_members select own family" on public.family_members
  for select to authenticated
  using (public.is_family_member(family_id));

-- family_members에 직접 insert하는 정책은 열어두지 않는다. 가입은 항상
-- create_family()/approve_join_request() 함수(security definer)를 통해서만 이뤄진다.

drop policy if exists "gifticons select family" on public.gifticons;
create policy "gifticons select family" on public.gifticons
  for select to authenticated
  using (public.is_family_member(family_id));

drop policy if exists "gifticons insert family" on public.gifticons;
create policy "gifticons insert family" on public.gifticons
  for insert to authenticated
  with check (public.is_family_member(family_id));

drop policy if exists "gifticons update family" on public.gifticons;
create policy "gifticons update family" on public.gifticons
  for update to authenticated
  using (public.is_family_member(family_id))
  with check (public.is_family_member(family_id));

drop policy if exists "gifticons delete family" on public.gifticons;
create policy "gifticons delete family" on public.gifticons
  for delete to authenticated
  using (public.is_family_member(family_id));

-- ===================== 이미지 스토리지 =====================

-- 기프티콘 이미지 저장소.
--
-- 예전에는 공개 버킷이었다. 주소만 알면 로그인 없이 누구나 볼 수 있었다는 뜻인데,
-- 기프티콘 사진에는 바코드가 찍혀 있다. 바코드는 그 자체가 돈이라, 주소 하나가 새면
-- 그 기프티콘은 남이 쓸 수 있다. 주소가 길고 어렵게 생긴 것은 방어가 아니다. 한 번
-- 새어 나간 주소는 영원히 유효했고, 가족에서 나간 사람이 예전에 본 주소를 계속 쓸 수도
-- 있었다.
--
-- 이제 비공개로 두고, 볼 자격이 있는 사람에게만 시간 제한이 붙은 주소를 발급해준다.
insert into storage.buckets (id, name, public)
values ('gifticon-images', 'gifticon-images', false)
on conflict (id) do nothing;

-- 이미 만들어져 있던 버킷도 비공개로 돌린다.
--
-- 크기·형식 제한도 함께 건다. 화면에도 같은 검사가 있지만 그건 편의를 위한 것이지 방어가
-- 아니다. 브라우저를 거치지 않고 스토리지 API를 직접 부르면 그 검사는 없는 것과 같아서,
-- 로그인만 하면 자기 가족 폴더에 아무 크기의 아무 파일이나 올릴 수 있었다.
-- (아이폰이 원본 그대로 올리는 경우가 있어 heic/heif도 받는다.)
update storage.buckets
set public = false,
    file_size_limit = 10485760,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif']
where id = 'gifticon-images';

-- 파일 경로의 첫 폴더(=family_id)를 안전하게 uuid로 파싱. 예전 방식(가족 폴더 없이 올라간 파일)이거나
-- 형식이 안 맞으면 null을 돌려줘서 정책 평가 중 에러 없이 그냥 "권한 없음"으로 처리되게 한다.
create or replace function public.storage_folder_family_id(object_name text)
returns uuid
language plpgsql
immutable
as $$
begin
  return (storage.foldername(object_name))[1]::uuid;
exception when others then
  return null;
end;
$$;

-- 볼 수 있는 사람 = 그 사진이 들어 있는 폴더(=family_id)의 구성원.
-- 이 정책이 "시간 제한 주소를 발급받을 자격"까지 정한다. 서명은 스토리지에 한 번 물어보고
-- 나오는 것이라, 여기서 막히면 주소 자체를 받을 수 없다.
-- 예전에는 to public이라 로그인조차 필요 없었다.
drop policy if exists "gifticon-images read" on storage.objects;
create policy "gifticon-images read"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'gifticon-images'
    and public.is_family_member(public.storage_folder_family_id(name))
  );

drop policy if exists "gifticon-images insert" on storage.objects;
create policy "gifticon-images insert"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'gifticon-images'
    and public.is_family_member(public.storage_folder_family_id(name))
  );

drop policy if exists "gifticon-images update" on storage.objects;
create policy "gifticon-images update"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'gifticon-images'
    and public.is_family_member(public.storage_folder_family_id(name))
  );

drop policy if exists "gifticon-images delete" on storage.objects;
create policy "gifticon-images delete"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'gifticon-images'
    and public.is_family_member(public.storage_folder_family_id(name))
  );

-- ===================== 유효기한 임박 푸시 알림 =====================

-- 브라우저 Push 구독 정보(기기별 1개). 한 사람이 여러 기기에서 알림을 켤 수도 있으니
-- user_id 기준 여러 행이 있을 수 있다.
create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  family_id uuid not null references public.families(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

-- 구독은 기기 하나에 하나이고 사람에게 딸린 것이다. family_id는 처음 알림을 켠 가족을
-- 적어둔 것뿐이라(실제 발송 대상은 family_members로 정한다), 그 가족이 없어졌다고 해서
-- 구독까지 같이 지워지면 다른 가족의 알림까지 끊긴다. 비워두는 것으로 바꾼다.
alter table public.push_subscriptions alter column family_id drop not null;

do $$
declare
  fk_name text;
begin
  select conname into fk_name
  from pg_constraint
  where conrelid = 'public.push_subscriptions'::regclass
    and contype = 'f'
    and confrelid = 'public.families'::regclass;

  if fk_name is not null then
    execute format('alter table public.push_subscriptions drop constraint %I', fk_name);
  end if;

  alter table public.push_subscriptions
    add constraint push_subscriptions_family_id_fkey
    foreign key (family_id) references public.families(id) on delete set null;
end $$;

alter table public.push_subscriptions enable row level security;

drop policy if exists "push_subscriptions manage own" on public.push_subscriptions;
create policy "push_subscriptions manage own" on public.push_subscriptions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and (family_id is null or public.is_family_member(family_id)));

-- 알림 구독 저장. 화면에서 upsert로 바로 넣지 않고 이 함수를 거친다.
--
-- endpoint는 "이 브라우저"를 가리키는 주소다. 사람이 아니라 기기에 딸린 값이라, 같은
-- 폰에서 다른 계정으로 로그인하면(구글로 들어왔다가 네이버로 들어오는 식) 그 주소를
-- 가진 줄이 예전 계정 소유로 남아 있다.
--
-- 그 상태에서 upsert(on conflict endpoint)를 하면 안쪽에서 update로 바뀌는데, update는
-- 위 정책의 using(user_id = auth.uid())을 예전 줄에 대고 따져본다. 남의 줄이니 거짓이고,
-- "new row violates row-level security policy (USING expression)"로 끊긴다. 화면에서는
-- 알림 설정 실패로만 보였다.
--
-- 브라우저의 지금 주인은 지금 로그인한 사람이다. 예전 줄을 지우고 새로 적는 게 맞다.
-- 그냥 두면 그 폰으로 예전 계정의 알림이 계속 온다.
create or replace function public.save_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_family_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '로그인이 필요해요.';
  end if;

  -- security definer라 RLS를 지나가므로, 정책이 하던 확인을 여기서 직접 한다.
  if p_family_id is not null and not public.is_family_member(p_family_id) then
    raise exception '이 가족의 구성원이 아니에요.';
  end if;

  delete from public.push_subscriptions where endpoint = p_endpoint;

  insert into public.push_subscriptions (user_id, family_id, endpoint, p256dh, auth)
  values (auth.uid(), p_family_id, p_endpoint, p_p256dh, p_auth);
end;
$$;

revoke all on function public.save_push_subscription(text, text, text, uuid) from public;
grant execute on function public.save_push_subscription(text, text, text, uuid) to authenticated;

-- 유효기한이 임박했다고 이미 알림을 보냈는지 표시. expires_at이 바뀌면(수정/재등록)
-- 다시 알려줘야 하니 아래 트리거로 자동으로 false로 되돌린다.
alter table public.gifticons add column if not exists expiry_notified boolean not null default false;

create or replace function public.reset_expiry_notified()
returns trigger
language plpgsql
as $$
begin
  if new.expires_at is distinct from old.expires_at then
    new.expiry_notified := false;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_reset_expiry_notified on public.gifticons;
create trigger trg_reset_expiry_notified
  before update on public.gifticons
  for each row execute function public.reset_expiry_notified();

-- ===================== 가족 참여 신청 =====================

-- 초대 코드만 알면 바로 들어올 수 있으면, 코드를 마구 넣어보다 우연히 맞힌 사람도 그 가족의
-- 기프티콘(=돈)을 전부 보게 된다. 코드를 길게 만드는 건 맞히는 데 드는 시간을 늘릴 뿐이라,
-- 아예 기존 구성원이 승인해야 들어오도록 한다. 코드는 그대로 짧게 두어도 된다.
create table if not exists public.family_join_requests (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  status text not null default 'pending', -- pending | approved | rejected
  created_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid references auth.users(id),
  unique (family_id, user_id)
);

alter table public.family_join_requests enable row level security;

-- 신청한 본인과 그 가족 구성원만 본다. 넣고 고치는 일은 아래 함수로만 한다.
drop policy if exists "join_requests select" on public.family_join_requests;
create policy "join_requests select" on public.family_join_requests
  for select to authenticated
  using (user_id = auth.uid() or public.is_family_member(family_id));

-- 초대 코드로 참여 신청. 코드가 맞아도 바로 들어가지지 않고 대기 상태가 된다.
create or replace function public.request_join_family(code text, member_name text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  found_family public.families;
  clean_name text := btrim(member_name);
begin
  if auth.uid() is null then
    raise exception '로그인이 필요해요.';
  end if;
  if clean_name = '' then
    raise exception '이름을 입력해주세요.';
  end if;
  if char_length(clean_name) > 20 then
    raise exception '이름은 20자까지 쓸 수 있어요.';
  end if;

  -- 초대 코드는 6자리라, 계속 넣어보면 언젠가는 맞는 코드를 찾을 수 있다. 맞혀도 승인이
  -- 있어야 들어오지만, 남의 가족에 참여 신청을 마구 보내는 것만으로도 성가신 일이 된다.
  -- 그래서 코드가 맞는지 확인하기 전에 시도 횟수부터 센다(틀린 시도도 세야 의미가 있다).
  if not (public.bump_api_usage(auth.uid(), 'join_attempt', 20)->>'allowed')::boolean then
    raise exception '초대 코드를 너무 여러 번 시도했어요. 내일 다시 시도해주세요.';
  end if;

  select * into found_family from public.families where invite_code = upper(btrim(code));
  if not found then
    raise exception '초대 코드를 찾을 수 없어요.';
  end if;

  -- 이미 그 가족이면 이름만 갱신하고 끝낸다.
  if exists (select 1 from public.family_members where family_id = found_family.id and user_id = auth.uid()) then
    update public.family_members set display_name = clean_name
    where family_id = found_family.id and user_id = auth.uid();
    return json_build_object('status', 'joined', 'family_id', found_family.id, 'family_name', found_family.name);
  end if;

  -- 예전에는 "구성원이 0명이면 승인해줄 사람이 없으니 그냥 들여보낸다"는 예외가 있었다.
  -- 그런데 가족을 나가도 가족은 남아 있었기 때문에, 다들 나가고 빈 껍데기만 남은 가족은
  -- 코드를 아는 사람이면 누구나 승인 없이 들어가는 문이 됐다. 지금은 마지막 사람이 나가면
  -- 가족을 통째로 지우므로(leave_family) 구성원 0명인 가족은 아예 존재하지 않는다.
  -- 만에 하나 남아 있더라도 승인 없이 들여보내지는 않는다.
  if not exists (select 1 from public.family_members where family_id = found_family.id) then
    raise exception '이 가족에는 아무도 없어서 승인해줄 사람이 없어요. 새 가족을 만들어주세요.';
  end if;

  insert into public.family_join_requests (family_id, user_id, display_name)
  values (found_family.id, auth.uid(), clean_name)
  on conflict (family_id, user_id) do update
    set display_name = excluded.display_name,
        status = 'pending',
        created_at = now(),
        decided_at = null,
        decided_by = null;

  return json_build_object('status', 'pending', 'family_id', found_family.id, 'family_name', found_family.name);
end;
$$;

-- 승인은 그 가족 구성원이면 누구나 할 수 있다. 만든 사람만 할 수 있게 하면 그 사람이
-- 폰을 안 보거나 가족을 나갔을 때 아무도 못 들어온다. 이미 들어와 있는 사람들은 서로
-- 기프티콘을 다 보는 사이라, 승인 권한을 나눠도 실질적으로 잃는 것이 없다.
create or replace function public.approve_join_request(request_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.family_join_requests;
begin
  select * into req from public.family_join_requests where id = request_id;
  if not found then
    raise exception '신청을 찾을 수 없어요.';
  end if;
  if not public.is_family_member(req.family_id) then
    raise exception '이 가족의 구성원만 승인할 수 있어요.';
  end if;
  if req.status <> 'pending' then
    return;
  end if;

  insert into public.family_members (family_id, user_id, display_name, tag_color)
  values (req.family_id, req.user_id, req.display_name, public.next_tag_color(req.family_id))
  on conflict (family_id, user_id) do update set display_name = excluded.display_name;

  update public.family_join_requests
  set status = 'approved', decided_at = now(), decided_by = auth.uid()
  where id = request_id;
end;
$$;

create or replace function public.reject_join_request(request_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  req public.family_join_requests;
begin
  select * into req from public.family_join_requests where id = request_id;
  if not found then
    raise exception '신청을 찾을 수 없어요.';
  end if;
  if not public.is_family_member(req.family_id) then
    raise exception '이 가족의 구성원만 거절할 수 있어요.';
  end if;

  update public.family_join_requests
  set status = 'rejected', decided_at = now(), decided_by = auth.uid()
  where id = request_id and status = 'pending';
end;
$$;

grant execute on function public.request_join_family(text, text) to authenticated;
grant execute on function public.approve_join_request(uuid) to authenticated;
grant execute on function public.reject_join_request(uuid) to authenticated;

-- 이 파일을 처음 실행하는 시점까지 이미 만들어져 있던 "구성원 0명인 가족"을 정리한다.
-- 예전에는 마지막 사람이 나가도 가족이 남았고, 남은 가족은 초대 코드만 알면 승인 없이
-- 들어갈 수 있는 문이었다(위 request_join_family의 옛 예외). 그 문을 닫아도 이미 생긴
-- 빈 가족은 그대로 남으니 여기서 함께 지운다.
-- 사진 파일은 SQL에서 지울 수 없어 스토리지에 남는다(아무도 볼 수 없는 파일이 된다).
delete from public.gifticons
where family_id is not null
  and not exists (select 1 from public.family_members fm where fm.family_id = gifticons.family_id);

delete from public.families f
where not exists (select 1 from public.family_members fm where fm.family_id = f.id);

-- ===================== 찜하기 =====================

-- "이건 내가 쓸게"를 가족에게 알려두는 표시. 같은 기프티콘을 두 사람이 쓰러 가는 일을
-- 막는 것이 목적이다.
--
-- 잠금이 아니라 표시다. 찜해둬도 다른 사람이 바코드를 열고 쓸 수 있다. 잠그면 찜해둔
-- 사람이 잊었을 때 아무도 못 쓰게 되는데, 그건 막으려던 것보다 나쁘다.
-- 그래서 찜을 푸는 것은 본인만 할 수 있어도 문제가 되지 않는다.
alter table public.gifticons add column if not exists claimed_by uuid references auth.users(id);
alter table public.gifticons add column if not exists claimed_at timestamptz;
-- 이름을 따로 적어두는 이유는 used_by_name과 같다. 그 사람이 가족에서 나가도 카드에
-- "누가 쓰기로 했는지"는 남아 있어야 한다.
alter table public.gifticons add column if not exists claimed_by_name text;

-- 한 사람만 찜할 수 있다. 둘이 찜하면 애초에 막으려던 중복이 그대로 생긴다.
--
-- 확인하고 나서 쓰는 두 단계로 나누면, 두 사람이 동시에 눌렀을 때 둘 다 "비어 있다"를
-- 읽고 지나간다. 조건을 update의 where에 넣어 한 문장으로 처리한다.
create or replace function public.claim_gifticon(gid bigint)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  my_name text;
  fid uuid;
  taken_by text;
  claimed int;
begin
  select family_id into fid from public.gifticons where id = gid;
  if fid is null then
    raise exception '기프티콘을 찾을 수 없어요.';
  end if;

  select display_name into my_name
  from public.family_members where family_id = fid and user_id = uid;
  if my_name is null then
    raise exception '이 가족의 구성원이 아니에요.';
  end if;

  update public.gifticons
  set claimed_by = uid, claimed_by_name = my_name, claimed_at = now()
  where id = gid and (claimed_by is null or claimed_by = uid);
  get diagnostics claimed = row_count;

  if claimed = 0 then
    select claimed_by_name into taken_by from public.gifticons where id = gid;
    return json_build_object('ok', false, 'claimed_by_name', taken_by);
  end if;

  return json_build_object('ok', true, 'claimed_by_name', my_name);
end;
$$;

-- 찜을 푸는 것은 본인만. 찜은 잠금이 아니라서, 남이 못 풀어도 쓰는 데 지장이 없다.
create or replace function public.release_gifticon(gid bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.gifticons
  set claimed_by = null, claimed_by_name = null, claimed_at = null
  where id = gid and claimed_by = auth.uid();
end;
$$;

grant execute on function public.claim_gifticon(bigint) to authenticated;
grant execute on function public.release_gifticon(bigint) to authenticated;

-- 다 쓴 기프티콘에 "내가 쓸게"가 남아 있으면 헷갈린다. 사용 완료로 바뀌면 찜을 지운다.
create or replace function public.clear_claim_when_used()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'used' and old.status is distinct from 'used' then
    new.claimed_by := null;
    new.claimed_by_name := null;
    new.claimed_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_clear_claim_when_used on public.gifticons;
create trigger trg_clear_claim_when_used
  before update on public.gifticons
  for each row execute function public.clear_claim_when_used();

-- ===================== 약관 동의 =====================

-- 문서를 만들어 두는 것과 이용자가 동의한 것은 다르다. 동의를 받은 기록이 없으면 약관은
-- 효력을 주장하기 어렵고, 스토어 심사에서도 가입 절차에 동의가 있는지를 본다.
--
-- 만 14세 확인을 함께 받는 이유: 개인정보보호법상 만 14세 미만은 법정대리인 동의가 있어야
-- 개인정보를 수집할 수 있다. 이 앱은 그 절차를 감당할 수 없으므로 만 14세 이상만 받는다.
--
-- 버전을 적어두면 약관을 고쳤을 때 누가 어느 판에 동의했는지 알 수 있고, 다시 받아야 할
-- 사람을 가려낼 수 있다.
create table if not exists public.user_consents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  is_over_14 boolean not null,
  agreed_at timestamptz not null default now()
);

alter table public.user_consents enable row level security;

-- 자기 동의 기록만 보고 남길 수 있다. 고치거나 지우는 정책은 두지 않는다.
-- 동의 기록은 "그때 이렇게 동의했다"는 사실이라 나중에 손대면 기록으로서 의미가 없다.
drop policy if exists "user_consents select own" on public.user_consents;
create policy "user_consents select own" on public.user_consents
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "user_consents insert own" on public.user_consents;
create policy "user_consents insert own" on public.user_consents
  for insert to authenticated
  with check (user_id = auth.uid() and is_over_14);

-- 약관을 고쳐 다시 동의를 받아야 할 때는 화면 쪽 버전 값을 올린다. 그러면 예전 판에
-- 동의한 사람에게 동의 화면이 다시 나타나므로, 여기서 기록을 지울 필요가 없다.
drop policy if exists "user_consents update own" on public.user_consents;
create policy "user_consents update own" on public.user_consents
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and is_over_14);

-- ===================== 공지 =====================

-- 운영자가 사용자 전체에게 알리는 글. 가족에 속하지 않는 글이라 family_id가 없다.
--
-- 쓰는 정책을 아예 두지 않는다. 브라우저에서는 어떤 계정으로도 공지를 쓸 수 없고,
-- 운영자가 SQL Editor(또는 서비스 롤)로만 넣는다. "관리자만 쓰기" 같은 정책을 두려면
-- 누가 관리자인지 표시하는 칸이 또 필요한데, 공지 몇 줄 넣자고 권한 체계를 만드는 건
-- 이 앱 크기에 맞지 않는다. 정책이 없으면 RLS가 전부 막으므로 그게 가장 단단하다.
create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  -- 미리 써두고 예약할 수 있게 시작 시각을 둔다. 지금 바로 띄우려면 now()를 넣는다.
  starts_at timestamptz not null default now(),
  -- 언제까지 보여줄지. 비워두면 계속 남는다(예: 이용 안내). 연휴 안내처럼 지나면
  -- 의미 없는 글은 끝 시각을 넣어두면 저절로 내려간다.
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

-- 목록 맨 위 띠에 띄울 만큼 급한 공지인지. 앱 위쪽에는 띠를 하나만 두기로 했고(둘이
-- 겹치면 목록이 두 줄만큼 밀린다), 평소 그 자리는 주변 매장 안내가 쓴다. 중요 공지가
-- 게시 중일 때만 그 자리를 가져간다.
--
-- 중요하지 않은 공지도 사라지지 않는다. 띠에 안 뜰 뿐, 종 아이콘 옆 "공지사항"에는
-- 그대로 쌓인다. 그래서 이 값은 "보여줄까 말까"가 아니라 "끼어들까 말까"에 가깝다.
alter table public.notices add column if not exists is_important boolean not null default false;

-- 마지막으로 손댄 시각. 화면에서 "이 공지를 닫았다"를 기억할 때 id가 아니라 id와 이 값을
-- 함께 쓴다.
--
-- 닫기를 id로만 기억하면, 한 번 닫은 공지는 그 기기에서 영영 다시 못 뜬다. 그런데 운영자가
-- 그 글을 고쳐서 다시 올리거나, 안내성이던 것을 중요로 올리는 일이 있다. 그때는 같은 공지라도
-- 다시 보여줘야 한다 — 사용자가 닫은 것은 "그때의 그 내용"이지 이 글의 모든 판이 아니다.
--
-- 반대로 아무도 손대지 않은 공지가 자꾸 되살아나면 닫기 버튼이 거짓말이 된다. 그래서
-- "고쳤을 때만" 되살아나게 이 값을 기준으로 삼는다.
alter table public.notices add column if not exists updated_at timestamptz not null default now();

create or replace function public.touch_notice_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists notices_touch_updated_at on public.notices;
create trigger notices_touch_updated_at
  before update on public.notices
  for each row execute function public.touch_notice_updated_at();

-- 이 공지가 뜬 동안에는 등록을 막을지.
--
-- is_important와 나눠 둔 이유가 있다. 유료화 안내도 중요 공지인데, 그게 등록을 막으면
-- 안 된다. "꼭 봐야 하는가"와 "지금 그 기능이 되는가"는 다른 이야기다.
--
-- 막는 것은 등록 하나다. 모델을 부르는 자리가 거기뿐이고, 바코드·목록·매장은 점검과
-- 무관하게 돌아간다. 계산대에서 바코드를 띄우는 사람은 점검 중인 줄도 모르고 잘 쓰고
-- 나가는데, 그게 맞는 결과다.
--
-- 무엇이 왜 막히는지는 공지 본문에 적는다. 여기서 종류를 나누지 않는다.
alter table public.notices add column if not exists blocks_upload boolean not null default false;

create index if not exists notices_starts_at_idx on public.notices (starts_at desc);

alter table public.notices enable row level security;

-- 공지는 가족과 무관하게 로그인한 사람 모두가 본다. 아직 시작 시각이 안 된 글은
-- 감춘다. 예약해둔 글이 미리 보이면 예약이 의미가 없다.
drop policy if exists "notices select all" on public.notices;
create policy "notices select all" on public.notices
  for select to authenticated
  using (starts_at <= now());

-- ===================== 공지 읽음 =====================

-- 어느 공지를 읽었는지. 기기가 아니라 계정에 적는다.
--
-- 종 배지가 안 읽은 활동과 안 읽은 공지를 함께 세기 때문이다. 활동 읽음은 서버에
-- 있는데(activity_reads) 공지 읽음만 기기에 있으면, 한 폰에서 읽고 다른 폰에서 보면
-- 숫자가 달라진다. 한 배지가 두 기준으로 세는 셈이다.
--
-- 폰을 바꿔도 유지된다는 것도 덤이다.
--
-- '읽었다'는 종을 연 것으로 친다. 공지가 목록 맨 위에 고정돼 있어 열면 무조건 보이고,
-- 한 번 더 누르게 하면 일만 는다.
create table if not exists public.notice_reads (
  user_id uuid not null references auth.users (id) on delete cascade,
  notice_id bigint not null references public.notices (id) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (user_id, notice_id)
);

alter table public.notice_reads enable row level security;

drop policy if exists "notice_reads own" on public.notice_reads;
create policy "notice_reads own" on public.notice_reads
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ===================== 앱 안 알림 (가족 활동) =====================

-- 가족이 기프티콘을 쓰거나 올리면 목록이 조용히 바뀔 뿐이라, "이거 누가 썼지?"를 알 방법이
-- 없었다. 그렇다고 폰을 울릴 일은 아니다. 그래서 푸시로는 보내지 않고 앱 안에서만 쌓아둔다.
--
-- 푸시로 나가는 것(유효기한 임박, 가족 참여 신청)과 성격이 다르다. 그 둘은 앱을 안 열고
-- 있어도 지금 알아야 하는 일이고, 이건 다음에 앱을 열었을 때 알면 되는 일이다.
--
-- 찜은 넣지 않는다. 찜/해제를 반복하면 목록이 시끄러워지는데, 누가 찜했는지는 이미
-- 카드 버튼에 "○○ 찜"으로 적혀 있어서 여기서 또 알릴 이유가 없다.
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  -- 'created'(등록) | 'used'(사용완료) | 'unused'(사용취소)
  kind text not null,
  actor_id uuid references auth.users(id) on delete set null,
  -- 이름을 따로 적어두는 이유는 used_by_name과 같다. 그 사람이 가족에서 나가거나 계정을
  -- 지워도 "누가 했는지"는 기록에 남아 있어야 한다.
  actor_name text,
  gifticon_id bigint references public.gifticons(id) on delete set null,
  -- 기프티콘이 지워져도 "무엇을 썼는지"는 남아야 해서 이름도 함께 적어둔다.
  gifticon_name text not null,
  -- 금액권을 쓴 경우 이번에 쓴 금액. 나머지 활동에서는 비어 있다.
  amount integer,
  created_at timestamptz not null default now()
);

alter table public.activities add column if not exists amount integer;

create index if not exists activities_family_idx on public.activities (family_id, created_at desc);

alter table public.activities enable row level security;

-- 우리 가족 것만 본다. 쓰기 정책은 두지 않는다. 기록은 아래 트리거가 남기므로 브라우저에서
-- 직접 넣을 일이 없고, 넣을 수 있으면 있지도 않은 일을 지어낼 수 있다.
drop policy if exists "activities select family" on public.activities;
create policy "activities select family" on public.activities
  for select to authenticated
  using (public.is_family_member(family_id));

-- 기록은 화면이 아니라 데이터베이스가 남긴다. 화면 코드에서 "사용완료를 눌렀으니 기록도
-- 남기자"로 하면, 나중에 다른 경로가 생겼을 때(관리자 화면, 일괄 처리 등) 빠뜨린다.
create or replace function public.log_gifticon_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  what text;
  who text;
  spent integer := null;
begin
  if TG_OP = 'INSERT' then
    what := 'created';
  elsif new.status is distinct from old.status then
    what := case when new.status = 'used' then 'used' else 'unused' end;
    -- 금액권을 마지막 한 번에 다 써서 사용완료로 넘어간 경우, 그 마지막 금액도 함께 적는다.
    if new.spent_amount > coalesce(old.spent_amount, 0) then
      spent := new.spent_amount - coalesce(old.spent_amount, 0);
    end if;
  elsif new.spent_amount is distinct from coalesce(old.spent_amount, 0) and new.spent_amount > coalesce(old.spent_amount, 0) then
    -- 금액권을 조금 썼다. 아직 잔액이 남아서 상태는 그대로다.
    what := 'spent';
    spent := new.spent_amount - coalesce(old.spent_amount, 0);
  else
    -- 이름이나 금액만 고친 것은 알릴 일이 아니다.
    return new;
  end if;

  -- ⚠️ 테스트 전용. 출시 전에 이 두 줄을 지운다(client/src/sampleData.js와 함께).
  -- 목데이터는 사람이 올린 것이 아니라 앱이 채워 넣은 것이라 알릴 일이 아니다. 그냥 두면
  -- 목데이터를 넣을 때마다 "태수님이 ○○ 올렸어요"가 아홉 줄씩 쌓이고, 목데이터를 지워도
  -- 그 줄은 남는다(알림은 기프티콘이 지워져도 기록으로 남게 만들어져 있다).
  if new.code like '9000111122%' then
    return new;
  end if;

  -- 가족에서 나간 사람의 기프티콘은 목록에 안 보이므로 알릴 것도 없다.
  if new.family_id is null or new.hidden_at is not null then
    return new;
  end if;

  select display_name into who
  from public.family_members
  where family_id = new.family_id and user_id = auth.uid();

  insert into public.activities (family_id, kind, actor_id, actor_name, gifticon_id, gifticon_name, amount)
  values (new.family_id, what, auth.uid(), coalesce(who, new.used_by_name, new.owner), new.id, new.name, spent);

  return new;
end;
$$;

drop trigger if exists gifticons_activity on public.gifticons;
create trigger gifticons_activity
  after insert or update of status, spent_amount on public.gifticons
  for each row execute function public.log_gifticon_activity();

-- 어디까지 봤는지. 항목마다 읽음 표시를 두지 않고 사람별로 "마지막으로 본 시각" 한 줄만
-- 남긴다. 안 읽은 개수는 그 시각 이후에 쌓인 것을 세면 되고, 기록이 아무리 늘어도
-- 이 표는 사람 수만큼만 자란다.
create table if not exists public.activity_reads (
  user_id uuid not null references auth.users(id) on delete cascade,
  family_id uuid not null references public.families(id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (user_id, family_id)
);

alter table public.activity_reads enable row level security;

drop policy if exists "activity_reads manage own" on public.activity_reads;
create policy "activity_reads manage own" on public.activity_reads
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- 오래된 기록은 지운다. 두 달 전에 누가 뭘 썼는지는 아무도 다시 보지 않는데, 안 지우면
-- 가족이 오래 쓸수록 목록만 길어진다. 사용 내역(사용 완료된 기프티콘)은 그대로 남으므로
-- "언제 썼나"를 되짚을 길이 사라지는 것도 아니다.
create or replace function public.purge_old_activities()
returns integer
language sql
security definer
set search_path = public
as $$
  with gone as (
    delete from public.activities where created_at < now() - interval '60 days' returning 1
  )
  select count(*)::integer from gone;
$$;

-- ===================== 외부 API 사용량 =====================

-- 돈이 나가는 기능(AI 분석, 가격 검색, 주변 매장)을 한 사람이 하루에 몇 번 썼는지 센다.
-- 로그인 확인만으로는 부족하다. 계정은 얼마든지 새로 만들 수 있어서, 사람 수가 아니라
-- 계정 수만큼 요금이 나갈 수 있기 때문이다. 여기서 사람당 상한을 둔다.
create table if not exists public.api_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  day date not null,
  count int not null default 0,
  primary key (user_id, action, day)
);

-- 사용자가 직접 들여다보거나 고칠 일이 없다. 정책을 하나도 만들지 않아서
-- (RLS는 켜져 있고 정책이 없으면 아무것도 통과하지 못한다) 서버만 다룬다.
alter table public.api_usage enable row level security;

-- 사람별 상한만으로는 부족하다. 계정은 이메일만 있으면 새로 만들 수 있어서, 계정을
-- 갈아치우며 부르면 사람별 상한은 매번 0부터 다시 시작한다. 그래서 "오늘 이 기능이
-- 전부 합쳐 몇 번 쓰였나"도 따로 세고, 거기에도 천장을 둔다. 요금이 얼마까지 나갈 수
-- 있는지를 이 숫자가 정한다.
create table if not exists public.api_usage_total (
  action text not null,
  day date not null,
  count int not null default 0,
  primary key (action, day)
);

alter table public.api_usage_total enable row level security;

-- 세는 일과 판단을 한 문장에서 한다. 나눠서 하면 동시에 여러 번 부를 때 둘 다
-- "아직 여유 있음"으로 읽고 지나가버린다.
-- (인자가 늘어서 예전 것을 지우고 다시 만든다)
drop function if exists public.bump_api_usage(uuid, text, int);
create or replace function public.bump_api_usage(uid uuid, act text, max_per_day int, max_total_per_day int default null)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  today date := (now() at time zone 'utc')::date;
  used int;
  total_used int;
begin
  insert into public.api_usage (user_id, action, day, count)
  values (uid, act, today, 1)
  on conflict (user_id, action, day) do update set count = public.api_usage.count + 1
  returning count into used;

  -- 자기 몫을 넘긴 사람은 여기서 끝낸다. 전체 숫자는 올리지 않는다.
  -- 올려버리면, 한 사람이 계속 두드리는 것만으로 그날 전체 몫이 바닥나서 아무도 못 쓰게
  -- 된다. 막으려던 것(요금)을 막다가 다른 것(서비스 정지)을 내주는 셈이다.
  if used > max_per_day then
    return json_build_object('allowed', false, 'reason', 'user', 'used', used, 'limit', max_per_day);
  end if;

  if max_total_per_day is not null then
    insert into public.api_usage_total (action, day, count)
    values (act, today, 1)
    on conflict (action, day) do update set count = public.api_usage_total.count + 1
    returning count into total_used;

    if total_used > max_total_per_day then
      -- 사용자 잘못이 아니다. 화면에도 다르게 말해야 한다.
      return json_build_object('allowed', false, 'reason', 'total', 'used', used, 'limit', max_per_day);
    end if;
  end if;

  return json_build_object('allowed', true, 'reason', null, 'used', used, 'limit', max_per_day);
end;
$$;

-- 이 함수를 사용자가 부를 수 있으면 남의 사용량을 마음대로 올려 못 쓰게 만들 수 있다.
-- 서버(Edge Function)와, 이 안에서 다시 부르는 security definer 함수만 부른다.
revoke all on function public.bump_api_usage(uuid, text, int, int) from public;
revoke all on function public.bump_api_usage(uuid, text, int, int) from anon;
revoke all on function public.bump_api_usage(uuid, text, int, int) from authenticated;
grant execute on function public.bump_api_usage(uuid, text, int, int) to service_role;

-- 오래된 기록은 쌓아둘 이유가 없다. 이 파일을 실행할 때마다 한 달 지난 것을 치운다.
-- 단 api_usage_total은 치우지 않는다. 사람별 기록(api_usage)은 한도 검사용이라 한 달이면
-- 충분하지만, 전체 기록은 관리자 대시보드(supabase/admin-stats.sql)가 일/월/연 호출 추이를
-- 그리는 원본이다. 하루에 기능당 한 줄이라 몇 년을 쌓아도 부담이 없다.
delete from public.api_usage where day < (now() at time zone 'utc')::date - 30;

-- ===================== 계정 탈퇴 =====================

-- '가족 나가기'와 다르다. 가족 나가기는 그 가족에서만 빠지고 계정과 다른 가족은 그대로지만,
-- 탈퇴는 계정 자체를 없앤다. 그래서 감추는 게 아니라 실제로 지운다.
--
-- 여기서는 데이터만 지운다. auth.users 행은 이 함수의 권한으로 지울 수 없어서,
-- supabase/functions/delete-account가 이 함수를 부른 뒤 사진 파일과 계정을 마저 지운다.
--
-- 남는 것: 다른 가족이 올린 기프티콘(그건 그 가족의 것이다)과, 내가 쓴 사용 내역의 줄.
-- 사용 내역은 가족이 "언제 뭘 썼나"를 보는 기록이라 통째로 지우면 가족 쪽 기록이 비는데,
-- 이름은 남기지 않도록 '탈퇴한 구성원'으로 바꾼다.
create or replace function public.purge_my_data()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  dead_families uuid[] := '{}';
  doomed bigint[] := '{}';
  paths text[] := '{}';
begin
  if uid is null then
    raise exception '로그인이 필요해요.';
  end if;

  -- 나 혼자 남아 있던 가족은 내가 빠지면 아무도 없으니 통째로 없어진다(가족 나가기와 같다).
  select coalesce(array_agg(fm.family_id), '{}') into dead_families
  from public.family_members fm
  where fm.user_id = uid
    and (select count(*) from public.family_members x where x.family_id = fm.family_id) = 1;

  -- 지울 기프티콘: 내가 올렸거나 내 앞으로 된 것, 그리고 없어질 가족에 남아 있는 것 전부.
  select coalesce(array_agg(g.id), '{}') into doomed
  from public.gifticons g
  where g.family_id = any(dead_families)
     or g.created_by = uid
     or exists (
       select 1 from public.family_members fm
       where fm.family_id = g.family_id and fm.user_id = uid and fm.display_name = g.owner
     );

  select coalesce(array_agg(p), '{}') into paths
  from (
    select unnest(image_paths) as p from public.gifticons where id = any(doomed)
    union all
    select barcode_image_path from public.gifticons where id = any(doomed) and barcode_image_path is not null
    union all
    select thumb_image_path from public.gifticons where id = any(doomed) and thumb_image_path is not null
  ) t;

  delete from public.gifticons where id = any(doomed);

  -- 남는 기프티콘에서 나를 가리키는 것들을 끊는다(계정이 지워지면 이 참조 때문에 막힌다).
  update public.gifticons set used_by = null, used_by_name = '탈퇴한 구성원' where used_by = uid;
  update public.gifticons set created_by = null where created_by = uid;
  update public.gifticons
  set claimed_by = null, claimed_by_name = null, claimed_at = null
  where claimed_by = uid;
  -- 메모를 남긴 사람. 이 줄이 없어서 메모를 한 번이라도 쓴 계정은 탈퇴가 막혔다 —
  -- 데이터는 다 지워지고 마지막 auth.users 삭제에서 이 참조 때문에 거절당한다.
  -- memo_by는 나중에 더한 칸인데 여기를 같이 안 고쳤다.
  update public.gifticons
  set memo_by = null, memo_by_name = '탈퇴한 구성원'
  where memo_by = uid;

  -- 스토리지에 남은 파일의 '주인' 표시.
  --
  -- 사진을 올리면 파일마다 올린 사람이 적히고, 그 칸도 auth.users를 가리킨다. 그래서
  -- 기프티콘을 다 지워도 파일이 남아 있으면 계정 삭제가 거기서 막힌다. 남는 파일은
  -- 늘 있다 — 예전에 지운 기프티콘의 잔여물, 올리다 만 사진 같은 것들이다.
  --
  -- 파일 자체는 여기서 지우지 않는다. 내가 올렸지만 남의 기프티콘에 붙어 있는 사진이
  -- 있을 수 있고(등록한 뒤 다른 사람이 사진을 더한 경우), 그걸 지우면 멀쩡한 기프티콘의
  -- 사진이 사라진다. 주인 표시만 끊는다.
  --
  -- 스토리지는 우리 스키마가 아니라 Supabase 것이라 판이 다를 수 있다(칸 이름이 다르거나
  -- 권한이 없을 수 있다). 그때는 그냥 넘어간다 — 여기서 멈추면 탈퇴 전체가 막힌다.
  begin
    execute 'update storage.objects set owner = null where owner = $1' using uid;
  exception when others then null;
  end;

  delete from public.push_subscriptions where user_id = uid;
  delete from public.family_join_requests where user_id = uid;
  update public.family_join_requests set decided_by = null where decided_by = uid;
  delete from public.family_members where user_id = uid;
  delete from public.families where id = any(dead_families);
  update public.families set created_by = null where created_by = uid;

  return json_build_object(
    'image_paths', paths,
    'deleted_gifticons', coalesce(array_length(doomed, 1), 0),
    'deleted_families', coalesce(array_length(dead_families, 1), 0)
  );
end;
$$;

grant execute on function public.purge_my_data() to authenticated;

-- 탈퇴가 막혔을 때, 무엇이 붙들고 있는지 이름으로 알려준다.
--
-- 이 기능은 같은 자리에서 세 번 막혔다. 그때마다 "이 칸이겠지" 하고 짚어 고쳤고, 세 번 다
-- 틀렸거나 절반만 맞았다. 화면에 오는 말이 "계정을 지우지 못했어요"뿐이라 다음에 볼 곳을
-- 고를 근거가 없었기 때문이다. 그래서 짐작하는 대신 데이터베이스에 직접 묻기로 한다.
--
-- 계정을 지우지 못하게 막을 수 있는 것은 auth.users를 가리키면서 '따라 지우기'도 '비우기'도
-- 아닌 참조뿐이다(confdeltype이 a=아무것도 안 함, r=거절). 그런 칸을 전부 찾아 이 계정을
-- 가리키는 줄이 남아 있는지 세어 본다. 우리 스키마만 보지 않는다 — 지금까지 우리를 막은
-- 것들은 대개 storage처럼 우리가 만들지 않은 자리에 있었다.
create or replace function public.user_delete_blockers(target uuid)
returns table (ref text, rows bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  r record;
  n bigint;
begin
  for r in
    select con.conrelid::regclass::text as tbl, att.attname::text as col
    from pg_constraint con
    join pg_class ref on ref.oid = con.confrelid
    join pg_namespace refns on refns.oid = ref.relnamespace
    join unnest(con.conkey) as k(attnum) on true
    join pg_attribute att on att.attrelid = con.conrelid and att.attnum = k.attnum
    where con.contype = 'f'
      and refns.nspname = 'auth'
      and ref.relname = 'users'
      and con.confdeltype in ('a', 'r')
  loop
    -- 볼 수 없는 표가 섞여 있어도 나머지는 마저 센다.
    begin
      execute format('select count(*) from %s where %I = $1', r.tbl, r.col) into n using target;
    exception when others then
      n := 0;
    end;
    if n > 0 then
      ref := r.tbl || '.' || r.col;
      rows := n;
      return next;
    end if;
  end loop;
end;
$$;

-- 남의 계정을 넣어 캐볼 수 있으므로 로그인한 사람에게는 주지 않는다. 서버(탈퇴 함수)만 쓴다.
revoke all on function public.user_delete_blockers(uuid) from public, anon, authenticated;
grant execute on function public.user_delete_blockers(uuid) to service_role;

-- ===================== 실시간 반영 =====================

-- 가족 중 누가 기프티콘을 올리거나 가족이 새로 들어오면, 다른 사람 화면에도 새로고침 없이
-- 바로 보이게 한다. 이 publication에 테이블을 넣어둬야 Supabase가 변경 사실을 앱으로 알려준다.
-- (누가 무엇을 받아볼지는 위의 RLS 정책이 그대로 판단하므로, 남의 가족 것은 오지 않는다.)
-- 이미 들어 있으면 다시 넣을 때 오류가 나므로 확인하고 넣는다.
do $$
declare
  target text;
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    return;
  end if;

  foreach target in array array['gifticons', 'family_members', 'families', 'family_join_requests', 'activities'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = target
    ) then
      execute format('alter publication supabase_realtime add table public.%I', target);
    end if;
  end loop;
end $$;
