-- Supabase SQL editor에서 이 파일 내용을 그대로 실행하세요.
-- (아직 로그인/권한 기능이 없으므로 지금은 RLS를 끄고 링크를 아는 사람만 접근한다는 전제로 둡니다.
--  나중에 인증을 붙일 때 이 부분을 다시 손보면 됩니다.)

create table if not exists public.gifticons (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default '기타',
  brand text,
  amount integer,
  owner text,
  code text,
  code_type text,
  expires_at date,
  memo text,
  image_path text,
  status text not null default 'unused',
  used_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gifticons disable row level security;

-- 이미지 저장용 public 버킷 생성
insert into storage.buckets (id, name, public)
values ('gifticon-images', 'gifticon-images', true)
on conflict (id) do nothing;

-- 버킷 안에서는 누구나(anon 포함) 읽기/쓰기/삭제 가능하도록 허용
-- (재실행해도 에러 안 나게 먼저 지우고 다시 만듭니다)
drop policy if exists "gifticon-images read" on storage.objects;
create policy "gifticon-images read"
  on storage.objects for select
  to public
  using (bucket_id = 'gifticon-images');

drop policy if exists "gifticon-images insert" on storage.objects;
create policy "gifticon-images insert"
  on storage.objects for insert
  to public
  with check (bucket_id = 'gifticon-images');

drop policy if exists "gifticon-images update" on storage.objects;
create policy "gifticon-images update"
  on storage.objects for update
  to public
  using (bucket_id = 'gifticon-images');

drop policy if exists "gifticon-images delete" on storage.objects;
create policy "gifticon-images delete"
  on storage.objects for delete
  to public
  using (bucket_id = 'gifticon-images');
