-- Supabase SQL editor에서 이 파일 내용을 그대로 실행하세요. 여러 번 실행해도 안전합니다(idempotent).
-- 로그인(이메일 매직링크) + 가족 그룹 공유를 지원합니다. 기프티콘은 family_id로 스코핑되고,
-- RLS(Row Level Security)로 "내가 속한 가족의 데이터만" 보이도록 강제합니다.

create extension if not exists pgcrypto;

create table if not exists public.gifticons (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default '기타',
  brand text,
  amount integer,
  owner text,
  code text,
  code_type text,
  expires_at date,
  memo text,
  image_paths text[] not null default '{}',
  status text not null default 'unused',
  used_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 예전에 이 파일을 이미 실행해서 image_path(단일) 컬럼이 있는 테이블이라면
-- 여러 장 업로드를 지원하는 image_paths(배열) 컬럼으로 옮겨준다.
alter table public.gifticons add column if not exists image_paths text[] not null default '{}';

-- 바코드 보기에서 원본 사진 대신 보여줄, 바코드/숫자 부분만 잘라낸 이미지
alter table public.gifticons add column if not exists barcode_image_path text;

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'gifticons' and column_name = 'image_path') then
    update public.gifticons
      set image_paths = array[image_path]
      where image_path is not null and (image_paths is null or array_length(image_paths, 1) is null);
    alter table public.gifticons drop column image_path;
  end if;
end $$;

-- ===================== 가족 그룹 (families / family_members) =====================

create table if not exists public.families (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  invite_code text not null unique,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.family_members (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now(),
  unique (family_id, user_id)
);

-- 기프티콘을 어느 가족 소유로 볼지 표시하는 컬럼
alter table public.gifticons add column if not exists family_id uuid references public.families(id);

-- 내가 이 family에 속해 있는지 확인하는 헬퍼 함수.
-- security definer라서 family_members 자체에 RLS가 걸려 있어도(재귀 없이) 안전하게 조회한다.
create or replace function public.is_family_member(fid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.family_members fm
    where fm.family_id = fid and fm.user_id = auth.uid()
  );
$$;

-- 가족 생성: families row + 만든 사람을 첫 멤버로 등록. 초대 코드는 6자리로 자동 생성.
create or replace function public.create_family(family_name text, member_name text)
returns public.families
language plpgsql
security definer
set search_path = public
as $$
declare
  new_family public.families;
  code text;
  attempt int := 0;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요해요.';
  end if;

  loop
    code := upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));
    begin
      insert into public.families (name, invite_code, created_by)
      values (family_name, code, auth.uid())
      returning * into new_family;
      exit;
    exception when unique_violation then
      attempt := attempt + 1;
      if attempt > 5 then
        raise exception '초대 코드 생성에 실패했어요. 다시 시도해주세요.';
      end if;
    end;
  end loop;

  insert into public.family_members (family_id, user_id, display_name)
  values (new_family.id, auth.uid(), member_name);

  return new_family;
end;
$$;

-- 초대 코드로 가족 참여. 이미 그 가족에 속해 있으면 표시 이름만 갱신한다.
create or replace function public.join_family(code text, member_name text)
returns public.families
language plpgsql
security definer
set search_path = public
as $$
declare
  found_family public.families;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요해요.';
  end if;

  select * into found_family from public.families where invite_code = upper(code);
  if not found then
    raise exception '초대 코드를 찾을 수 없어요.';
  end if;

  insert into public.family_members (family_id, user_id, display_name)
  values (found_family.id, auth.uid(), member_name)
  on conflict (family_id, user_id) do update set display_name = excluded.display_name;

  return found_family;
end;
$$;

grant execute on function public.create_family(text, text) to authenticated;
grant execute on function public.join_family(text, text) to authenticated;

alter table public.families enable row level security;
alter table public.family_members enable row level security;
alter table public.gifticons enable row level security;

drop policy if exists "families select own" on public.families;
create policy "families select own" on public.families
  for select to authenticated
  using (public.is_family_member(id));

drop policy if exists "family_members select own family" on public.family_members;
create policy "family_members select own family" on public.family_members
  for select to authenticated
  using (public.is_family_member(family_id));

-- family_members에 직접 insert하는 정책은 열어두지 않는다. 가입은 항상
-- create_family()/join_family() 함수(security definer)를 통해서만 이뤄진다.

drop policy if exists "gifticons select family" on public.gifticons;
create policy "gifticons select family" on public.gifticons
  for select to authenticated
  using (public.is_family_member(family_id));

drop policy if exists "gifticons insert family" on public.gifticons;
create policy "gifticons insert family" on public.gifticons
  for insert to authenticated
  with check (public.is_family_member(family_id));

drop policy if exists "gifticons update family" on public.gifticons;
create policy "gifticons update family" on public.gifticons
  for update to authenticated
  using (public.is_family_member(family_id))
  with check (public.is_family_member(family_id));

drop policy if exists "gifticons delete family" on public.gifticons;
create policy "gifticons delete family" on public.gifticons
  for delete to authenticated
  using (public.is_family_member(family_id));

-- ===================== 이미지 스토리지 =====================

-- 이미지 저장용 public 버킷 생성 (이미지 자체는 지금처럼 URL을 아는 사람이면 볼 수 있는 공개 버킷으로 유지.
-- 업로드/수정/삭제만 그 가족 폴더(family_id/파일명)에 속한 로그인 사용자로 제한한다.)
insert into storage.buckets (id, name, public)
values ('gifticon-images', 'gifticon-images', true)
on conflict (id) do nothing;

-- 파일 경로의 첫 폴더(=family_id)를 안전하게 uuid로 파싱. 예전 방식(가족 폴더 없이 올라간 파일)이거나
-- 형식이 안 맞으면 null을 돌려줘서 정책 평가 중 에러 없이 그냥 "권한 없음"으로 처리되게 한다.
create or replace function public.storage_folder_family_id(object_name text)
returns uuid
language plpgsql
immutable
as $$
begin
  return (storage.foldername(object_name))[1]::uuid;
exception when others then
  return null;
end;
$$;

drop policy if exists "gifticon-images read" on storage.objects;
create policy "gifticon-images read"
  on storage.objects for select
  to public
  using (bucket_id = 'gifticon-images');

drop policy if exists "gifticon-images insert" on storage.objects;
create policy "gifticon-images insert"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'gifticon-images'
    and public.is_family_member(public.storage_folder_family_id(name))
  );

drop policy if exists "gifticon-images update" on storage.objects;
create policy "gifticon-images update"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'gifticon-images'
    and public.is_family_member(public.storage_folder_family_id(name))
  );

drop policy if exists "gifticon-images delete" on storage.objects;
create policy "gifticon-images delete"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'gifticon-images'
    and public.is_family_member(public.storage_folder_family_id(name))
  );

-- ===================== 유효기한 임박 푸시 알림 =====================

-- 브라우저 Push 구독 정보(기기별 1개). 한 사람이 여러 기기에서 알림을 켤 수도 있으니
-- user_id 기준 여러 행이 있을 수 있다.
create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  family_id uuid not null references public.families(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "push_subscriptions manage own" on public.push_subscriptions;
create policy "push_subscriptions manage own" on public.push_subscriptions
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid() and public.is_family_member(family_id));

-- 유효기한이 임박했다고 이미 알림을 보냈는지 표시. expires_at이 바뀌면(수정/재등록)
-- 다시 알려줘야 하니 아래 트리거로 자동으로 false로 되돌린다.
alter table public.gifticons add column if not exists expiry_notified boolean not null default false;

create or replace function public.reset_expiry_notified()
returns trigger
language plpgsql
as $$
begin
  if new.expires_at is distinct from old.expires_at then
    new.expiry_notified := false;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_reset_expiry_notified on public.gifticons;
create trigger trg_reset_expiry_notified
  before update on public.gifticons
  for each row execute function public.reset_expiry_notified();
